// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/errcode.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrCode int32

const (
	ErrCode_OK                    ErrCode = 0
	ErrCode_Error                 ErrCode = 1
	ErrCode_Busy                  ErrCode = 2
	ErrCode_UserAlreadyLogin      ErrCode = 10
	ErrCode_GroupNotExist         ErrCode = 11
	ErrCode_UserNotInGroup        ErrCode = 12
	ErrCode_UserNotExist          ErrCode = 13
	ErrCode_UserNotHasPermission  ErrCode = 14
	ErrCode_RequestArgumentErr    ErrCode = 1001
	ErrCode_FriendAlreadyIsFriend ErrCode = 1101
	ErrCode_FriendApplyClosed     ErrCode = 1102
)

var ErrCode_name = map[int32]string{
	0:    "OK",
	1:    "Error",
	2:    "Busy",
	10:   "UserAlreadyLogin",
	11:   "GroupNotExist",
	12:   "UserNotInGroup",
	13:   "UserNotExist",
	14:   "UserNotHasPermission",
	1001: "RequestArgumentErr",
	1101: "FriendAlreadyIsFriend",
	1102: "FriendApplyClosed",
}

var ErrCode_value = map[string]int32{
	"OK":                    0,
	"Error":                 1,
	"Busy":                  2,
	"UserAlreadyLogin":      10,
	"GroupNotExist":         11,
	"UserNotInGroup":        12,
	"UserNotExist":          13,
	"UserNotHasPermission":  14,
	"RequestArgumentErr":    1001,
	"FriendAlreadyIsFriend": 1101,
	"FriendApplyClosed":     1102,
}

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}

func (x *ErrCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrCode_value, data, "ErrCode")
	if err != nil {
		return err
	}
	*x = ErrCode(value)
	return nil
}

func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7a5460248a277878, []int{0}
}

type Extra struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Extra) Reset()         { *m = Extra{} }
func (m *Extra) String() string { return proto.CompactTextString(m) }
func (*Extra) ProtoMessage()    {}
func (*Extra) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a5460248a277878, []int{0}
}

func (m *Extra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extra.Unmarshal(m, b)
}
func (m *Extra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extra.Marshal(b, m, deterministic)
}
func (m *Extra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extra.Merge(m, src)
}
func (m *Extra) XXX_Size() int {
	return xxx_messageInfo_Extra.Size(m)
}
func (m *Extra) XXX_DiscardUnknown() {
	xxx_messageInfo_Extra.DiscardUnknown(m)
}

var xxx_messageInfo_Extra proto.InternalMessageInfo

func (m *Extra) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Extra) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.IM.ErrCode", ErrCode_name, ErrCode_value)
	proto.RegisterType((*Extra)(nil), "message.IM.Extra")
}

func init() { proto.RegisterFile("protocol/errcode.proto", fileDescriptor_7a5460248a277878) }

var fileDescriptor_7a5460248a277878 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0x41, 0x4e, 0xf2, 0x60,
	0x10, 0x86, 0x7f, 0xfa, 0x8b, 0x94, 0x11, 0xc8, 0x30, 0xa9, 0xd8, 0xb8, 0x32, 0xae, 0x8c, 0x0b,
	0x38, 0x03, 0x90, 0xaa, 0x8d, 0x8a, 0x86, 0xc4, 0x8d, 0xbb, 0x86, 0x4e, 0x9a, 0xc6, 0xb6, 0x53,
	0xe7, 0xfb, 0x6a, 0xe8, 0x21, 0xf5, 0x04, 0x5e, 0xc0, 0x5b, 0x18, 0xda, 0xba, 0x9b, 0xf7, 0x79,
	0x9f, 0xc5, 0xe4, 0x85, 0x59, 0xa9, 0x62, 0x65, 0x27, 0xd9, 0x82, 0x55, 0x77, 0x12, 0xf3, 0xbc,
	0x01, 0x04, 0x39, 0x1b, 0x13, 0x25, 0x3c, 0x0f, 0x1f, 0x2f, 0x17, 0xd0, 0x0f, 0xf6, 0x56, 0x23,
	0x42, 0xf8, 0xff, 0xc6, 0xb5, 0xdf, 0xbb, 0x70, 0xae, 0x86, 0xdb, 0xc3, 0x49, 0x1e, 0xf4, 0x3f,
	0xa2, 0xac, 0x62, 0xdf, 0x69, 0x58, 0x1b, 0xae, 0xbf, 0x7b, 0x30, 0x08, 0x54, 0xd7, 0x12, 0x33,
	0x1d, 0x83, 0xf3, 0x74, 0x8f, 0xff, 0x68, 0x08, 0xfd, 0x40, 0x55, 0x14, 0x7b, 0xe4, 0xc2, 0xd1,
	0xaa, 0x32, 0x35, 0x3a, 0xe4, 0x01, 0xbe, 0x18, 0xd6, 0x65, 0xa6, 0x1c, 0xc5, 0xf5, 0x83, 0x24,
	0x69, 0x81, 0x40, 0x53, 0x18, 0xdf, 0xaa, 0x54, 0xe5, 0x46, 0x6c, 0xb0, 0x4f, 0x8d, 0xc5, 0x13,
	0x22, 0x98, 0x1c, 0xc4, 0x8d, 0xd8, 0xb0, 0x68, 0x3a, 0x1c, 0x11, 0xc2, 0xa8, 0x63, 0xad, 0x35,
	0x26, 0x1f, 0xbc, 0x8e, 0xdc, 0x45, 0xe6, 0x99, 0x35, 0x4f, 0x8d, 0x49, 0xa5, 0xc0, 0x09, 0x9d,
	0x01, 0x6d, 0xf9, 0xbd, 0x62, 0x63, 0x97, 0x9a, 0x54, 0x39, 0x17, 0x36, 0x50, 0xc5, 0x9f, 0x01,
	0x9d, 0xc3, 0xe9, 0x8d, 0xa6, 0x5c, 0xc4, 0xdd, 0x0f, 0xa1, 0x69, 0x23, 0x7e, 0xba, 0x34, 0x83,
	0x69, 0xd7, 0x95, 0x65, 0x56, 0xaf, 0x33, 0x31, 0x1c, 0xe3, 0x97, 0xbb, 0x82, 0x57, 0xf7, 0x6f,
	0xb5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xaf, 0x0a, 0x03, 0x40, 0x01, 0x00, 0x00,
}
