// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/user.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserLoginReq struct {
	ID                   *string  `protobuf:"bytes,1,req,name=ID" json:"ID,omitempty"`
	Extras               []*Extra `protobuf:"bytes,2,rep,name=extras" json:"extras,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginReq) Reset()         { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()    {}
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{0}
}

func (m *UserLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginReq.Unmarshal(m, b)
}
func (m *UserLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginReq.Marshal(b, m, deterministic)
}
func (m *UserLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginReq.Merge(m, src)
}
func (m *UserLoginReq) XXX_Size() int {
	return xxx_messageInfo_UserLoginReq.Size(m)
}
func (m *UserLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginReq proto.InternalMessageInfo

func (m *UserLoginReq) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

func (m *UserLoginReq) GetExtras() []*Extra {
	if m != nil {
		return m.Extras
	}
	return nil
}

type UserLoginResp struct {
	Code                 *ErrCode `protobuf:"varint,1,opt,name=code,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResp) Reset()         { *m = UserLoginResp{} }
func (m *UserLoginResp) String() string { return proto.CompactTextString(m) }
func (*UserLoginResp) ProtoMessage()    {}
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{1}
}

func (m *UserLoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResp.Unmarshal(m, b)
}
func (m *UserLoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResp.Marshal(b, m, deterministic)
}
func (m *UserLoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResp.Merge(m, src)
}
func (m *UserLoginResp) XXX_Size() int {
	return xxx_messageInfo_UserLoginResp.Size(m)
}
func (m *UserLoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResp proto.InternalMessageInfo

func (m *UserLoginResp) GetCode() ErrCode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ErrCode_OK
}

type Heartbeat struct {
	Timestamp            *int64   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{2}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*UserLoginReq)(nil), "UserLoginReq")
	proto.RegisterType((*UserLoginResp)(nil), "UserLoginResp")
	proto.RegisterType((*Heartbeat)(nil), "Heartbeat")
}

func init() { proto.RegisterFile("protocol/user.proto", fileDescriptor_fe658c3c35e8c4bc) }

var fileDescriptor_fe658c3c35e8c4bc = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x03, 0xf3, 0xa4, 0xc4, 0xe0, 0x82,
	0xa9, 0x45, 0x45, 0xc9, 0xf9, 0x29, 0xa9, 0x10, 0x71, 0x25, 0x3b, 0x2e, 0x9e, 0xd0, 0xe2, 0xd4,
	0x22, 0x9f, 0xfc, 0xf4, 0xcc, 0xbc, 0xa0, 0xd4, 0x42, 0x21, 0x3e, 0x2e, 0x26, 0x4f, 0x17, 0x09,
	0x46, 0x05, 0x26, 0x0d, 0xce, 0x20, 0x26, 0x4f, 0x17, 0x21, 0x39, 0x2e, 0xb6, 0xd4, 0x8a, 0x92,
	0xa2, 0xc4, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x36, 0x3d, 0x57, 0x10, 0x37, 0x08,
	0x2a, 0xaa, 0xa4, 0xcb, 0xc5, 0x8b, 0xa4, 0xbf, 0xb8, 0x40, 0x48, 0x86, 0x8b, 0x05, 0x64, 0xbc,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x9f, 0x11, 0x87, 0x9e, 0x6b, 0x51, 0x91, 0x73, 0x7e, 0x4a, 0x6a,
	0x10, 0x58, 0x54, 0x49, 0x93, 0x8b, 0xd3, 0x23, 0x35, 0xb1, 0xa8, 0x24, 0x29, 0x35, 0xb1, 0x44,
	0x48, 0x86, 0x8b, 0xb3, 0x24, 0x33, 0x37, 0xb5, 0xb8, 0x24, 0x31, 0xb7, 0x00, 0xac, 0x9e, 0x39,
	0x08, 0x21, 0xe0, 0xc4, 0x15, 0xc5, 0x01, 0x73, 0x33, 0x20, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x3f,
	0x86, 0x57, 0xd3, 0x00, 0x00, 0x00,
}
