Address           = "10.128.2.123:43210"
MaxConnCount      = 5000             # 最大用户链接数
HeartbeatTimeout  = 10               # 心跳超时时间，单位秒。
MaxBackups        = 3                # 聊天记录保留的表数量
MaxMessageCount   = 200              # 每个会话最大消息缓存
MaxTaskCount      = 2048             # 任务队列容量

[DBConfig]
SqlType               = "postgres"
Host                  = "localhost"
Port                  = 5432
User		          = "dbuser"
Password              = "123456"
Database              = "yidongdeng"

[LogConfig]
Path            = "log"
Filename        = "im"
MaxSize         = 0      #日志大小，单位 M。如为0，则不创建日志文件
Debug           = true
EnableStdout    = true