// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conversation.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConversationType int32

const (
	ConversationType_Normal    ConversationType = 0
	ConversationType_Transient ConversationType = 1
	ConversationType_ChatRoom  ConversationType = 2
)

var ConversationType_name = map[int32]string{
	0: "Normal",
	1: "Transient",
	2: "ChatRoom",
}

var ConversationType_value = map[string]int32{
	"Normal":    0,
	"Transient": 1,
	"ChatRoom":  2,
}

func (x ConversationType) String() string {
	return proto.EnumName(ConversationType_name, int32(x))
}

func (ConversationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{0}
}

type Conversation struct {
	Type                 ConversationType  `protobuf:"varint,1,opt,name=type,proto3,enum=ConversationType" json:"type,omitempty"`
	ID                   int64             `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Extra                map[string]string `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	LastMessageID        int64             `protobuf:"varint,4,opt,name=lastMessageID,proto3" json:"lastMessageID,omitempty"`
	LastMessageAt        int64             `protobuf:"varint,5,opt,name=lastMessageAt,proto3" json:"lastMessageAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Conversation) Reset()         { *m = Conversation{} }
func (m *Conversation) String() string { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()    {}
func (*Conversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{0}
}

func (m *Conversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation.Unmarshal(m, b)
}
func (m *Conversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation.Marshal(b, m, deterministic)
}
func (m *Conversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation.Merge(m, src)
}
func (m *Conversation) XXX_Size() int {
	return xxx_messageInfo_Conversation.Size(m)
}
func (m *Conversation) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation proto.InternalMessageInfo

func (m *Conversation) GetType() ConversationType {
	if m != nil {
		return m.Type
	}
	return ConversationType_Normal
}

func (m *Conversation) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Conversation) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *Conversation) GetLastMessageID() int64 {
	if m != nil {
		return m.LastMessageID
	}
	return 0
}

func (m *Conversation) GetLastMessageAt() int64 {
	if m != nil {
		return m.LastMessageAt
	}
	return 0
}

// 创建对话
type CreateConversationReq struct {
	Members              []string          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Extra                map[string]string `protobuf:"bytes,2,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateConversationReq) Reset()         { *m = CreateConversationReq{} }
func (m *CreateConversationReq) String() string { return proto.CompactTextString(m) }
func (*CreateConversationReq) ProtoMessage()    {}
func (*CreateConversationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{1}
}

func (m *CreateConversationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationReq.Unmarshal(m, b)
}
func (m *CreateConversationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationReq.Marshal(b, m, deterministic)
}
func (m *CreateConversationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationReq.Merge(m, src)
}
func (m *CreateConversationReq) XXX_Size() int {
	return xxx_messageInfo_CreateConversationReq.Size(m)
}
func (m *CreateConversationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationReq proto.InternalMessageInfo

func (m *CreateConversationReq) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *CreateConversationReq) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

type CreateConversationResp struct {
	Code                 ErrCode       `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Conv                 *Conversation `protobuf:"bytes,2,opt,name=conv,proto3" json:"conv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateConversationResp) Reset()         { *m = CreateConversationResp{} }
func (m *CreateConversationResp) String() string { return proto.CompactTextString(m) }
func (*CreateConversationResp) ProtoMessage()    {}
func (*CreateConversationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{2}
}

func (m *CreateConversationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationResp.Unmarshal(m, b)
}
func (m *CreateConversationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationResp.Marshal(b, m, deterministic)
}
func (m *CreateConversationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationResp.Merge(m, src)
}
func (m *CreateConversationResp) XXX_Size() int {
	return xxx_messageInfo_CreateConversationResp.Size(m)
}
func (m *CreateConversationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationResp proto.InternalMessageInfo

func (m *CreateConversationResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *CreateConversationResp) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

type NotifyInvited struct {
	Conv                 *Conversation `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	InitBy               string        `protobuf:"bytes,2,opt,name=initBy,proto3" json:"initBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NotifyInvited) Reset()         { *m = NotifyInvited{} }
func (m *NotifyInvited) String() string { return proto.CompactTextString(m) }
func (*NotifyInvited) ProtoMessage()    {}
func (*NotifyInvited) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{3}
}

func (m *NotifyInvited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyInvited.Unmarshal(m, b)
}
func (m *NotifyInvited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyInvited.Marshal(b, m, deterministic)
}
func (m *NotifyInvited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyInvited.Merge(m, src)
}
func (m *NotifyInvited) XXX_Size() int {
	return xxx_messageInfo_NotifyInvited.Size(m)
}
func (m *NotifyInvited) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyInvited.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyInvited proto.InternalMessageInfo

func (m *NotifyInvited) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

func (m *NotifyInvited) GetInitBy() string {
	if m != nil {
		return m.InitBy
	}
	return ""
}

// 用户发送消息
type Message struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type MessageInfo struct {
	Msg                  *Message `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	CreateAt             int64    `protobuf:"varint,3,opt,name=createAt,proto3" json:"createAt,omitempty"`
	MsgID                int64    `protobuf:"varint,4,opt,name=msgID,proto3" json:"msgID,omitempty"`
	Recalled             bool     `protobuf:"varint,5,opt,name=recalled,proto3" json:"recalled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageInfo) Reset()         { *m = MessageInfo{} }
func (m *MessageInfo) String() string { return proto.CompactTextString(m) }
func (*MessageInfo) ProtoMessage()    {}
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{5}
}

func (m *MessageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageInfo.Unmarshal(m, b)
}
func (m *MessageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageInfo.Marshal(b, m, deterministic)
}
func (m *MessageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageInfo.Merge(m, src)
}
func (m *MessageInfo) XXX_Size() int {
	return xxx_messageInfo_MessageInfo.Size(m)
}
func (m *MessageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MessageInfo proto.InternalMessageInfo

func (m *MessageInfo) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *MessageInfo) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *MessageInfo) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *MessageInfo) GetMsgID() int64 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

func (m *MessageInfo) GetRecalled() bool {
	if m != nil {
		return m.Recalled
	}
	return false
}

type SendMessageReq struct {
	ConvID               int64    `protobuf:"varint,1,opt,name=convID,proto3" json:"convID,omitempty"`
	Msg                  *Message `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageReq) Reset()         { *m = SendMessageReq{} }
func (m *SendMessageReq) String() string { return proto.CompactTextString(m) }
func (*SendMessageReq) ProtoMessage()    {}
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{6}
}

func (m *SendMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageReq.Unmarshal(m, b)
}
func (m *SendMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageReq.Marshal(b, m, deterministic)
}
func (m *SendMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageReq.Merge(m, src)
}
func (m *SendMessageReq) XXX_Size() int {
	return xxx_messageInfo_SendMessageReq.Size(m)
}
func (m *SendMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageReq proto.InternalMessageInfo

func (m *SendMessageReq) GetConvID() int64 {
	if m != nil {
		return m.ConvID
	}
	return 0
}

func (m *SendMessageReq) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type SendMessageResp struct {
	Code                 ErrCode       `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Conv                 *Conversation `protobuf:"bytes,2,opt,name=conv,proto3" json:"conv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SendMessageResp) Reset()         { *m = SendMessageResp{} }
func (m *SendMessageResp) String() string { return proto.CompactTextString(m) }
func (*SendMessageResp) ProtoMessage()    {}
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{7}
}

func (m *SendMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResp.Unmarshal(m, b)
}
func (m *SendMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResp.Marshal(b, m, deterministic)
}
func (m *SendMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResp.Merge(m, src)
}
func (m *SendMessageResp) XXX_Size() int {
	return xxx_messageInfo_SendMessageResp.Size(m)
}
func (m *SendMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResp proto.InternalMessageInfo

func (m *SendMessageResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *SendMessageResp) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

type NotifyMessage struct {
	Conv                 *Conversation  `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	MsgInfos             []*MessageInfo `protobuf:"bytes,2,rep,name=msgInfos,proto3" json:"msgInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NotifyMessage) Reset()         { *m = NotifyMessage{} }
func (m *NotifyMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyMessage) ProtoMessage()    {}
func (*NotifyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{8}
}

func (m *NotifyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMessage.Unmarshal(m, b)
}
func (m *NotifyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMessage.Marshal(b, m, deterministic)
}
func (m *NotifyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMessage.Merge(m, src)
}
func (m *NotifyMessage) XXX_Size() int {
	return xxx_messageInfo_NotifyMessage.Size(m)
}
func (m *NotifyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMessage proto.InternalMessageInfo

func (m *NotifyMessage) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

func (m *NotifyMessage) GetMsgInfos() []*MessageInfo {
	if m != nil {
		return m.MsgInfos
	}
	return nil
}

type AddMemberReq struct {
	ConvID               int64    `protobuf:"varint,1,opt,name=convID,proto3" json:"convID,omitempty"`
	AddIds               []string `protobuf:"bytes,2,rep,name=addIds,proto3" json:"addIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMemberReq) Reset()         { *m = AddMemberReq{} }
func (m *AddMemberReq) String() string { return proto.CompactTextString(m) }
func (*AddMemberReq) ProtoMessage()    {}
func (*AddMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{9}
}

func (m *AddMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMemberReq.Unmarshal(m, b)
}
func (m *AddMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMemberReq.Marshal(b, m, deterministic)
}
func (m *AddMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMemberReq.Merge(m, src)
}
func (m *AddMemberReq) XXX_Size() int {
	return xxx_messageInfo_AddMemberReq.Size(m)
}
func (m *AddMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddMemberReq proto.InternalMessageInfo

func (m *AddMemberReq) GetConvID() int64 {
	if m != nil {
		return m.ConvID
	}
	return 0
}

func (m *AddMemberReq) GetAddIds() []string {
	if m != nil {
		return m.AddIds
	}
	return nil
}

type AddMemberResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMemberResp) Reset()         { *m = AddMemberResp{} }
func (m *AddMemberResp) String() string { return proto.CompactTextString(m) }
func (*AddMemberResp) ProtoMessage()    {}
func (*AddMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{10}
}

func (m *AddMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMemberResp.Unmarshal(m, b)
}
func (m *AddMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMemberResp.Marshal(b, m, deterministic)
}
func (m *AddMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMemberResp.Merge(m, src)
}
func (m *AddMemberResp) XXX_Size() int {
	return xxx_messageInfo_AddMemberResp.Size(m)
}
func (m *AddMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddMemberResp proto.InternalMessageInfo

func (m *AddMemberResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

type NotifyMemberJoined struct {
	Conv                 *Conversation `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	JoinIds              []string      `protobuf:"bytes,2,rep,name=joinIds,proto3" json:"joinIds,omitempty"`
	InitBy               string        `protobuf:"bytes,3,opt,name=initBy,proto3" json:"initBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NotifyMemberJoined) Reset()         { *m = NotifyMemberJoined{} }
func (m *NotifyMemberJoined) String() string { return proto.CompactTextString(m) }
func (*NotifyMemberJoined) ProtoMessage()    {}
func (*NotifyMemberJoined) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{11}
}

func (m *NotifyMemberJoined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMemberJoined.Unmarshal(m, b)
}
func (m *NotifyMemberJoined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMemberJoined.Marshal(b, m, deterministic)
}
func (m *NotifyMemberJoined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMemberJoined.Merge(m, src)
}
func (m *NotifyMemberJoined) XXX_Size() int {
	return xxx_messageInfo_NotifyMemberJoined.Size(m)
}
func (m *NotifyMemberJoined) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMemberJoined.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMemberJoined proto.InternalMessageInfo

func (m *NotifyMemberJoined) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

func (m *NotifyMemberJoined) GetJoinIds() []string {
	if m != nil {
		return m.JoinIds
	}
	return nil
}

func (m *NotifyMemberJoined) GetInitBy() string {
	if m != nil {
		return m.InitBy
	}
	return ""
}

type RemoveMemberReq struct {
	ConvID               int64    `protobuf:"varint,1,opt,name=convID,proto3" json:"convID,omitempty"`
	RemoveIds            []string `protobuf:"bytes,2,rep,name=removeIds,proto3" json:"removeIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveMemberReq) Reset()         { *m = RemoveMemberReq{} }
func (m *RemoveMemberReq) String() string { return proto.CompactTextString(m) }
func (*RemoveMemberReq) ProtoMessage()    {}
func (*RemoveMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{12}
}

func (m *RemoveMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMemberReq.Unmarshal(m, b)
}
func (m *RemoveMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMemberReq.Marshal(b, m, deterministic)
}
func (m *RemoveMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMemberReq.Merge(m, src)
}
func (m *RemoveMemberReq) XXX_Size() int {
	return xxx_messageInfo_RemoveMemberReq.Size(m)
}
func (m *RemoveMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMemberReq proto.InternalMessageInfo

func (m *RemoveMemberReq) GetConvID() int64 {
	if m != nil {
		return m.ConvID
	}
	return 0
}

func (m *RemoveMemberReq) GetRemoveIds() []string {
	if m != nil {
		return m.RemoveIds
	}
	return nil
}

type RemoveMemberResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveMemberResp) Reset()         { *m = RemoveMemberResp{} }
func (m *RemoveMemberResp) String() string { return proto.CompactTextString(m) }
func (*RemoveMemberResp) ProtoMessage()    {}
func (*RemoveMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{13}
}

func (m *RemoveMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMemberResp.Unmarshal(m, b)
}
func (m *RemoveMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMemberResp.Marshal(b, m, deterministic)
}
func (m *RemoveMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMemberResp.Merge(m, src)
}
func (m *RemoveMemberResp) XXX_Size() int {
	return xxx_messageInfo_RemoveMemberResp.Size(m)
}
func (m *RemoveMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMemberResp proto.InternalMessageInfo

func (m *RemoveMemberResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

type NotifyMemberLeft struct {
	Conv                 *Conversation `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	LeftIds              []string      `protobuf:"bytes,2,rep,name=leftIds,proto3" json:"leftIds,omitempty"`
	KickedBy             string        `protobuf:"bytes,3,opt,name=kickedBy,proto3" json:"kickedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NotifyMemberLeft) Reset()         { *m = NotifyMemberLeft{} }
func (m *NotifyMemberLeft) String() string { return proto.CompactTextString(m) }
func (*NotifyMemberLeft) ProtoMessage()    {}
func (*NotifyMemberLeft) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{14}
}

func (m *NotifyMemberLeft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMemberLeft.Unmarshal(m, b)
}
func (m *NotifyMemberLeft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMemberLeft.Marshal(b, m, deterministic)
}
func (m *NotifyMemberLeft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMemberLeft.Merge(m, src)
}
func (m *NotifyMemberLeft) XXX_Size() int {
	return xxx_messageInfo_NotifyMemberLeft.Size(m)
}
func (m *NotifyMemberLeft) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMemberLeft.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMemberLeft proto.InternalMessageInfo

func (m *NotifyMemberLeft) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

func (m *NotifyMemberLeft) GetLeftIds() []string {
	if m != nil {
		return m.LeftIds
	}
	return nil
}

func (m *NotifyMemberLeft) GetKickedBy() string {
	if m != nil {
		return m.KickedBy
	}
	return ""
}

type NotifyKicked struct {
	Conv                 *Conversation `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	KickedBy             string        `protobuf:"bytes,2,opt,name=kickedBy,proto3" json:"kickedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NotifyKicked) Reset()         { *m = NotifyKicked{} }
func (m *NotifyKicked) String() string { return proto.CompactTextString(m) }
func (*NotifyKicked) ProtoMessage()    {}
func (*NotifyKicked) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{15}
}

func (m *NotifyKicked) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyKicked.Unmarshal(m, b)
}
func (m *NotifyKicked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyKicked.Marshal(b, m, deterministic)
}
func (m *NotifyKicked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyKicked.Merge(m, src)
}
func (m *NotifyKicked) XXX_Size() int {
	return xxx_messageInfo_NotifyKicked.Size(m)
}
func (m *NotifyKicked) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyKicked.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyKicked proto.InternalMessageInfo

func (m *NotifyKicked) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

func (m *NotifyKicked) GetKickedBy() string {
	if m != nil {
		return m.KickedBy
	}
	return ""
}

type JoinReq struct {
	ConvID               int64    `protobuf:"varint,1,opt,name=convID,proto3" json:"convID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinReq) Reset()         { *m = JoinReq{} }
func (m *JoinReq) String() string { return proto.CompactTextString(m) }
func (*JoinReq) ProtoMessage()    {}
func (*JoinReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{16}
}

func (m *JoinReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinReq.Unmarshal(m, b)
}
func (m *JoinReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinReq.Marshal(b, m, deterministic)
}
func (m *JoinReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinReq.Merge(m, src)
}
func (m *JoinReq) XXX_Size() int {
	return xxx_messageInfo_JoinReq.Size(m)
}
func (m *JoinReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinReq proto.InternalMessageInfo

func (m *JoinReq) GetConvID() int64 {
	if m != nil {
		return m.ConvID
	}
	return 0
}

type JoinResp struct {
	Code                 ErrCode       `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Conv                 *Conversation `protobuf:"bytes,2,opt,name=conv,proto3" json:"conv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *JoinResp) Reset()         { *m = JoinResp{} }
func (m *JoinResp) String() string { return proto.CompactTextString(m) }
func (*JoinResp) ProtoMessage()    {}
func (*JoinResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{17}
}

func (m *JoinResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResp.Unmarshal(m, b)
}
func (m *JoinResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResp.Marshal(b, m, deterministic)
}
func (m *JoinResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResp.Merge(m, src)
}
func (m *JoinResp) XXX_Size() int {
	return xxx_messageInfo_JoinResp.Size(m)
}
func (m *JoinResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResp proto.InternalMessageInfo

func (m *JoinResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *JoinResp) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

// 主动
type QuitReq struct {
	ConvID               int64    `protobuf:"varint,1,opt,name=convID,proto3" json:"convID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitReq) Reset()         { *m = QuitReq{} }
func (m *QuitReq) String() string { return proto.CompactTextString(m) }
func (*QuitReq) ProtoMessage()    {}
func (*QuitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{18}
}

func (m *QuitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitReq.Unmarshal(m, b)
}
func (m *QuitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitReq.Marshal(b, m, deterministic)
}
func (m *QuitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitReq.Merge(m, src)
}
func (m *QuitReq) XXX_Size() int {
	return xxx_messageInfo_QuitReq.Size(m)
}
func (m *QuitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitReq.DiscardUnknown(m)
}

var xxx_messageInfo_QuitReq proto.InternalMessageInfo

func (m *QuitReq) GetConvID() int64 {
	if m != nil {
		return m.ConvID
	}
	return 0
}

type QuitResp struct {
	Code                 ErrCode       `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Conv                 *Conversation `protobuf:"bytes,2,opt,name=conv,proto3" json:"conv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QuitResp) Reset()         { *m = QuitResp{} }
func (m *QuitResp) String() string { return proto.CompactTextString(m) }
func (*QuitResp) ProtoMessage()    {}
func (*QuitResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{19}
}

func (m *QuitResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitResp.Unmarshal(m, b)
}
func (m *QuitResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitResp.Marshal(b, m, deterministic)
}
func (m *QuitResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitResp.Merge(m, src)
}
func (m *QuitResp) XXX_Size() int {
	return xxx_messageInfo_QuitResp.Size(m)
}
func (m *QuitResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitResp.DiscardUnknown(m)
}

var xxx_messageInfo_QuitResp proto.InternalMessageInfo

func (m *QuitResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *QuitResp) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

// 获取会话的成员列表，对于像「聊天室」这样的特殊对话，并不存在「成员列表」属性
type GetConversationUsersReq struct {
	ConvID               int64    `protobuf:"varint,1,opt,name=convID,proto3" json:"convID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConversationUsersReq) Reset()         { *m = GetConversationUsersReq{} }
func (m *GetConversationUsersReq) String() string { return proto.CompactTextString(m) }
func (*GetConversationUsersReq) ProtoMessage()    {}
func (*GetConversationUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{20}
}

func (m *GetConversationUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationUsersReq.Unmarshal(m, b)
}
func (m *GetConversationUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationUsersReq.Marshal(b, m, deterministic)
}
func (m *GetConversationUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationUsersReq.Merge(m, src)
}
func (m *GetConversationUsersReq) XXX_Size() int {
	return xxx_messageInfo_GetConversationUsersReq.Size(m)
}
func (m *GetConversationUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationUsersReq proto.InternalMessageInfo

func (m *GetConversationUsersReq) GetConvID() int64 {
	if m != nil {
		return m.ConvID
	}
	return 0
}

type GetConversationUsersResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConversationUsersResp) Reset()         { *m = GetConversationUsersResp{} }
func (m *GetConversationUsersResp) String() string { return proto.CompactTextString(m) }
func (*GetConversationUsersResp) ProtoMessage()    {}
func (*GetConversationUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{21}
}

func (m *GetConversationUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationUsersResp.Unmarshal(m, b)
}
func (m *GetConversationUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationUsersResp.Marshal(b, m, deterministic)
}
func (m *GetConversationUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationUsersResp.Merge(m, src)
}
func (m *GetConversationUsersResp) XXX_Size() int {
	return xxx_messageInfo_GetConversationUsersResp.Size(m)
}
func (m *GetConversationUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationUsersResp proto.InternalMessageInfo

func (m *GetConversationUsersResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *GetConversationUsersResp) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// 解散会话
type DissolveConversationReq struct {
	ConvID               int64    `protobuf:"varint,1,opt,name=convID,proto3" json:"convID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DissolveConversationReq) Reset()         { *m = DissolveConversationReq{} }
func (m *DissolveConversationReq) String() string { return proto.CompactTextString(m) }
func (*DissolveConversationReq) ProtoMessage()    {}
func (*DissolveConversationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{22}
}

func (m *DissolveConversationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DissolveConversationReq.Unmarshal(m, b)
}
func (m *DissolveConversationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DissolveConversationReq.Marshal(b, m, deterministic)
}
func (m *DissolveConversationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DissolveConversationReq.Merge(m, src)
}
func (m *DissolveConversationReq) XXX_Size() int {
	return xxx_messageInfo_DissolveConversationReq.Size(m)
}
func (m *DissolveConversationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DissolveConversationReq.DiscardUnknown(m)
}

var xxx_messageInfo_DissolveConversationReq proto.InternalMessageInfo

func (m *DissolveConversationReq) GetConvID() int64 {
	if m != nil {
		return m.ConvID
	}
	return 0
}

type DissolveConversationResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DissolveConversationResp) Reset()         { *m = DissolveConversationResp{} }
func (m *DissolveConversationResp) String() string { return proto.CompactTextString(m) }
func (*DissolveConversationResp) ProtoMessage()    {}
func (*DissolveConversationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{23}
}

func (m *DissolveConversationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DissolveConversationResp.Unmarshal(m, b)
}
func (m *DissolveConversationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DissolveConversationResp.Marshal(b, m, deterministic)
}
func (m *DissolveConversationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DissolveConversationResp.Merge(m, src)
}
func (m *DissolveConversationResp) XXX_Size() int {
	return xxx_messageInfo_DissolveConversationResp.Size(m)
}
func (m *DissolveConversationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DissolveConversationResp.DiscardUnknown(m)
}

var xxx_messageInfo_DissolveConversationResp proto.InternalMessageInfo

func (m *DissolveConversationResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

type NotifyDissolveConversation struct {
	ConvID               int64    `protobuf:"varint,1,opt,name=convID,proto3" json:"convID,omitempty"`
	InitBy               string   `protobuf:"bytes,2,opt,name=initBy,proto3" json:"initBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyDissolveConversation) Reset()         { *m = NotifyDissolveConversation{} }
func (m *NotifyDissolveConversation) String() string { return proto.CompactTextString(m) }
func (*NotifyDissolveConversation) ProtoMessage()    {}
func (*NotifyDissolveConversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{24}
}

func (m *NotifyDissolveConversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyDissolveConversation.Unmarshal(m, b)
}
func (m *NotifyDissolveConversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyDissolveConversation.Marshal(b, m, deterministic)
}
func (m *NotifyDissolveConversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyDissolveConversation.Merge(m, src)
}
func (m *NotifyDissolveConversation) XXX_Size() int {
	return xxx_messageInfo_NotifyDissolveConversation.Size(m)
}
func (m *NotifyDissolveConversation) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyDissolveConversation.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyDissolveConversation proto.InternalMessageInfo

func (m *NotifyDissolveConversation) GetConvID() int64 {
	if m != nil {
		return m.ConvID
	}
	return 0
}

func (m *NotifyDissolveConversation) GetInitBy() string {
	if m != nil {
		return m.InitBy
	}
	return ""
}

// 拉取列表
type GetConversationListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConversationListReq) Reset()         { *m = GetConversationListReq{} }
func (m *GetConversationListReq) String() string { return proto.CompactTextString(m) }
func (*GetConversationListReq) ProtoMessage()    {}
func (*GetConversationListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{25}
}

func (m *GetConversationListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationListReq.Unmarshal(m, b)
}
func (m *GetConversationListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationListReq.Marshal(b, m, deterministic)
}
func (m *GetConversationListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationListReq.Merge(m, src)
}
func (m *GetConversationListReq) XXX_Size() int {
	return xxx_messageInfo_GetConversationListReq.Size(m)
}
func (m *GetConversationListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationListReq proto.InternalMessageInfo

type GetConversationListResp struct {
	Code                 ErrCode         `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Convs                []*Conversation `protobuf:"bytes,2,rep,name=convs,proto3" json:"convs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetConversationListResp) Reset()         { *m = GetConversationListResp{} }
func (m *GetConversationListResp) String() string { return proto.CompactTextString(m) }
func (*GetConversationListResp) ProtoMessage()    {}
func (*GetConversationListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{26}
}

func (m *GetConversationListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationListResp.Unmarshal(m, b)
}
func (m *GetConversationListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationListResp.Marshal(b, m, deterministic)
}
func (m *GetConversationListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationListResp.Merge(m, src)
}
func (m *GetConversationListResp) XXX_Size() int {
	return xxx_messageInfo_GetConversationListResp.Size(m)
}
func (m *GetConversationListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationListResp proto.InternalMessageInfo

func (m *GetConversationListResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *GetConversationListResp) GetConvs() []*Conversation {
	if m != nil {
		return m.Convs
	}
	return nil
}

// 会话消息同步
type SyncMessageReq struct {
	ConvID               int64    `protobuf:"varint,1,opt,name=convID,proto3" json:"convID,omitempty"`
	StartID              int64    `protobuf:"varint,2,opt,name=startID,proto3" json:"startID,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	OldToNew             bool     `protobuf:"varint,4,opt,name=oldToNew,proto3" json:"oldToNew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncMessageReq) Reset()         { *m = SyncMessageReq{} }
func (m *SyncMessageReq) String() string { return proto.CompactTextString(m) }
func (*SyncMessageReq) ProtoMessage()    {}
func (*SyncMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{27}
}

func (m *SyncMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessageReq.Unmarshal(m, b)
}
func (m *SyncMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessageReq.Marshal(b, m, deterministic)
}
func (m *SyncMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessageReq.Merge(m, src)
}
func (m *SyncMessageReq) XXX_Size() int {
	return xxx_messageInfo_SyncMessageReq.Size(m)
}
func (m *SyncMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessageReq proto.InternalMessageInfo

func (m *SyncMessageReq) GetConvID() int64 {
	if m != nil {
		return m.ConvID
	}
	return 0
}

func (m *SyncMessageReq) GetStartID() int64 {
	if m != nil {
		return m.StartID
	}
	return 0
}

func (m *SyncMessageReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SyncMessageReq) GetOldToNew() bool {
	if m != nil {
		return m.OldToNew
	}
	return false
}

type SyncMessageResp struct {
	Code                 ErrCode        `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Conv                 *Conversation  `protobuf:"bytes,2,opt,name=conv,proto3" json:"conv,omitempty"`
	MsgInfos             []*MessageInfo `protobuf:"bytes,3,rep,name=msgInfos,proto3" json:"msgInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SyncMessageResp) Reset()         { *m = SyncMessageResp{} }
func (m *SyncMessageResp) String() string { return proto.CompactTextString(m) }
func (*SyncMessageResp) ProtoMessage()    {}
func (*SyncMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{28}
}

func (m *SyncMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessageResp.Unmarshal(m, b)
}
func (m *SyncMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessageResp.Marshal(b, m, deterministic)
}
func (m *SyncMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessageResp.Merge(m, src)
}
func (m *SyncMessageResp) XXX_Size() int {
	return xxx_messageInfo_SyncMessageResp.Size(m)
}
func (m *SyncMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessageResp proto.InternalMessageInfo

func (m *SyncMessageResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *SyncMessageResp) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

func (m *SyncMessageResp) GetMsgInfos() []*MessageInfo {
	if m != nil {
		return m.MsgInfos
	}
	return nil
}

type RecallMessageReq struct {
	ConvID               int64    `protobuf:"varint,1,opt,name=convID,proto3" json:"convID,omitempty"`
	MsgID                int64    `protobuf:"varint,2,opt,name=msgID,proto3" json:"msgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecallMessageReq) Reset()         { *m = RecallMessageReq{} }
func (m *RecallMessageReq) String() string { return proto.CompactTextString(m) }
func (*RecallMessageReq) ProtoMessage()    {}
func (*RecallMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{29}
}

func (m *RecallMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecallMessageReq.Unmarshal(m, b)
}
func (m *RecallMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecallMessageReq.Marshal(b, m, deterministic)
}
func (m *RecallMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecallMessageReq.Merge(m, src)
}
func (m *RecallMessageReq) XXX_Size() int {
	return xxx_messageInfo_RecallMessageReq.Size(m)
}
func (m *RecallMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecallMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecallMessageReq proto.InternalMessageInfo

func (m *RecallMessageReq) GetConvID() int64 {
	if m != nil {
		return m.ConvID
	}
	return 0
}

func (m *RecallMessageReq) GetMsgID() int64 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

type RecallMessageResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecallMessageResp) Reset()         { *m = RecallMessageResp{} }
func (m *RecallMessageResp) String() string { return proto.CompactTextString(m) }
func (*RecallMessageResp) ProtoMessage()    {}
func (*RecallMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{30}
}

func (m *RecallMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecallMessageResp.Unmarshal(m, b)
}
func (m *RecallMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecallMessageResp.Marshal(b, m, deterministic)
}
func (m *RecallMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecallMessageResp.Merge(m, src)
}
func (m *RecallMessageResp) XXX_Size() int {
	return xxx_messageInfo_RecallMessageResp.Size(m)
}
func (m *RecallMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RecallMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_RecallMessageResp proto.InternalMessageInfo

func (m *RecallMessageResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

type NotifyRecallMessage struct {
	Conv                 *Conversation `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	Msg                  *MessageInfo  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NotifyRecallMessage) Reset()         { *m = NotifyRecallMessage{} }
func (m *NotifyRecallMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyRecallMessage) ProtoMessage()    {}
func (*NotifyRecallMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{31}
}

func (m *NotifyRecallMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRecallMessage.Unmarshal(m, b)
}
func (m *NotifyRecallMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRecallMessage.Marshal(b, m, deterministic)
}
func (m *NotifyRecallMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRecallMessage.Merge(m, src)
}
func (m *NotifyRecallMessage) XXX_Size() int {
	return xxx_messageInfo_NotifyRecallMessage.Size(m)
}
func (m *NotifyRecallMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRecallMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRecallMessage proto.InternalMessageInfo

func (m *NotifyRecallMessage) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

func (m *NotifyRecallMessage) GetMsg() *MessageInfo {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterEnum("ConversationType", ConversationType_name, ConversationType_value)
	proto.RegisterType((*Conversation)(nil), "Conversation")
	proto.RegisterMapType((map[string]string)(nil), "Conversation.ExtraEntry")
	proto.RegisterType((*CreateConversationReq)(nil), "CreateConversationReq")
	proto.RegisterMapType((map[string]string)(nil), "CreateConversationReq.ExtraEntry")
	proto.RegisterType((*CreateConversationResp)(nil), "CreateConversationResp")
	proto.RegisterType((*NotifyInvited)(nil), "NotifyInvited")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*MessageInfo)(nil), "MessageInfo")
	proto.RegisterType((*SendMessageReq)(nil), "SendMessageReq")
	proto.RegisterType((*SendMessageResp)(nil), "SendMessageResp")
	proto.RegisterType((*NotifyMessage)(nil), "NotifyMessage")
	proto.RegisterType((*AddMemberReq)(nil), "AddMemberReq")
	proto.RegisterType((*AddMemberResp)(nil), "AddMemberResp")
	proto.RegisterType((*NotifyMemberJoined)(nil), "NotifyMemberJoined")
	proto.RegisterType((*RemoveMemberReq)(nil), "RemoveMemberReq")
	proto.RegisterType((*RemoveMemberResp)(nil), "RemoveMemberResp")
	proto.RegisterType((*NotifyMemberLeft)(nil), "NotifyMemberLeft")
	proto.RegisterType((*NotifyKicked)(nil), "NotifyKicked")
	proto.RegisterType((*JoinReq)(nil), "JoinReq")
	proto.RegisterType((*JoinResp)(nil), "JoinResp")
	proto.RegisterType((*QuitReq)(nil), "QuitReq")
	proto.RegisterType((*QuitResp)(nil), "QuitResp")
	proto.RegisterType((*GetConversationUsersReq)(nil), "GetConversationUsersReq")
	proto.RegisterType((*GetConversationUsersResp)(nil), "GetConversationUsersResp")
	proto.RegisterType((*DissolveConversationReq)(nil), "DissolveConversationReq")
	proto.RegisterType((*DissolveConversationResp)(nil), "DissolveConversationResp")
	proto.RegisterType((*NotifyDissolveConversation)(nil), "NotifyDissolveConversation")
	proto.RegisterType((*GetConversationListReq)(nil), "GetConversationListReq")
	proto.RegisterType((*GetConversationListResp)(nil), "GetConversationListResp")
	proto.RegisterType((*SyncMessageReq)(nil), "SyncMessageReq")
	proto.RegisterType((*SyncMessageResp)(nil), "SyncMessageResp")
	proto.RegisterType((*RecallMessageReq)(nil), "RecallMessageReq")
	proto.RegisterType((*RecallMessageResp)(nil), "RecallMessageResp")
	proto.RegisterType((*NotifyRecallMessage)(nil), "NotifyRecallMessage")
}

func init() { proto.RegisterFile("conversation.proto", fileDescriptor_d6ae46d001825652) }

var fileDescriptor_d6ae46d001825652 = []byte{
	// 879 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0x76, 0xd2, 0x24, 0xa7, 0x49, 0x9b, 0x1d, 0xa0, 0x58, 0x61, 0x41, 0xed, 0x00, 0x52,
	0x84, 0x84, 0xc5, 0x96, 0x0b, 0x2a, 0x90, 0x10, 0xdd, 0xa6, 0x5a, 0x65, 0xb7, 0xad, 0xc4, 0x6c,
	0x57, 0x02, 0xb4, 0x37, 0x6e, 0x7c, 0x52, 0x4c, 0x6d, 0x4f, 0x76, 0x66, 0x1a, 0x36, 0x12, 0xef,
	0xc0, 0x4b, 0xf0, 0x96, 0xdc, 0xa0, 0x19, 0xff, 0xd4, 0x4e, 0xb3, 0x71, 0xa4, 0xed, 0x9d, 0xbf,
	0x39, 0x73, 0x7e, 0xbe, 0x73, 0x3e, 0xcf, 0x0c, 0x90, 0x09, 0x4f, 0xe6, 0x28, 0xa4, 0xaf, 0x42,
	0x9e, 0x78, 0x33, 0xc1, 0x15, 0x1f, 0xf4, 0x50, 0x88, 0x09, 0x0f, 0x30, 0x83, 0x70, 0x2b, 0x51,
	0xa4, 0xdf, 0xf4, 0x3f, 0x0b, 0xba, 0x27, 0x25, 0x0f, 0xf2, 0x15, 0x34, 0xd4, 0x62, 0x86, 0xae,
	0xb5, 0x6f, 0x0d, 0x77, 0x0e, 0x1f, 0x79, 0x65, 0xe3, 0xe5, 0x62, 0x86, 0xcc, 0x98, 0xc9, 0x0e,
	0xd8, 0xe3, 0x91, 0x6b, 0xef, 0x5b, 0x43, 0x87, 0xd9, 0xe3, 0x11, 0xf1, 0xa0, 0x89, 0x6f, 0x95,
	0xf0, 0x5d, 0x67, 0xdf, 0x19, 0x6e, 0x1f, 0xba, 0x15, 0x3f, 0xef, 0x54, 0x9b, 0x4e, 0x13, 0x25,
	0x16, 0x2c, 0xdd, 0x46, 0xbe, 0x84, 0x5e, 0xe4, 0x4b, 0x75, 0x8e, 0x52, 0xfa, 0xd7, 0x38, 0x1e,
	0xb9, 0x0d, 0x13, 0xaa, 0xba, 0xb8, 0xb4, 0xeb, 0x58, 0xb9, 0xcd, 0x7b, 0xbb, 0x8e, 0xd5, 0xe0,
	0x08, 0xe0, 0x2e, 0x01, 0xe9, 0x83, 0x73, 0x83, 0x0b, 0x53, 0x7f, 0x87, 0xe9, 0x4f, 0xf2, 0x11,
	0x34, 0xe7, 0x7e, 0x74, 0x8b, 0xa6, 0xdc, 0x0e, 0x4b, 0xc1, 0x0f, 0xf6, 0x91, 0x45, 0xff, 0xb5,
	0xe0, 0xe3, 0x13, 0x81, 0xbe, 0xc2, 0x72, 0xb9, 0x0c, 0xdf, 0x10, 0x17, 0x5a, 0x31, 0xc6, 0x57,
	0x28, 0xa4, 0x6b, 0xed, 0x3b, 0xc3, 0x0e, 0xcb, 0x21, 0xf9, 0x3e, 0x67, 0x6a, 0x1b, 0xa6, 0x07,
	0xde, 0xca, 0x00, 0xf7, 0x29, 0xbf, 0x47, 0x99, 0xbf, 0xc1, 0xde, 0xaa, 0x24, 0x72, 0x46, 0x1e,
	0x43, 0x43, 0x0f, 0x36, 0x9b, 0x56, 0xdb, 0x3b, 0x15, 0xe2, 0x84, 0x07, 0xc8, 0xcc, 0x2a, 0x39,
	0xd0, 0xd6, 0x64, 0x6e, 0x02, 0x6e, 0x1f, 0xf6, 0x2a, 0x33, 0x61, 0xc6, 0x44, 0x9f, 0x43, 0xef,
	0x82, 0xab, 0x70, 0xba, 0x18, 0x27, 0xf3, 0x50, 0x61, 0x50, 0xf8, 0x58, 0xef, 0xf4, 0x21, 0x7b,
	0xb0, 0x15, 0x26, 0xa1, 0x7a, 0xba, 0xc8, 0x2a, 0xcd, 0x10, 0xfd, 0x0c, 0x5a, 0xd9, 0x50, 0x08,
	0x81, 0x86, 0xc2, 0xb7, 0x2a, 0xa3, 0x67, 0xbe, 0xe9, 0x3f, 0x16, 0x6c, 0xe7, 0xa3, 0x4d, 0xa6,
	0x9c, 0x0c, 0xc0, 0x89, 0xe5, 0x75, 0x96, 0xa8, 0xed, 0x65, 0x26, 0xa6, 0x17, 0x75, 0x0a, 0x2d,
	0xd2, 0x4c, 0x62, 0x1d, 0x96, 0x21, 0x32, 0x80, 0xf6, 0xc4, 0x74, 0xe2, 0x58, 0xb9, 0x8e, 0xd1,
	0x42, 0x81, 0x75, 0xff, 0x62, 0x79, 0x5d, 0x48, 0x29, 0x05, 0xda, 0x43, 0xe0, 0xc4, 0x8f, 0x22,
	0x0c, 0x8c, 0x7a, 0xda, 0xac, 0xc0, 0x74, 0x04, 0x3b, 0x2f, 0x31, 0x09, 0xf2, 0xcc, 0xf8, 0x46,
	0xe7, 0xd5, 0x14, 0xc7, 0x23, 0x53, 0x96, 0xc3, 0x32, 0x94, 0xd7, 0x6a, 0xaf, 0xa8, 0x95, 0x32,
	0xd8, 0xad, 0x44, 0x79, 0x88, 0xb1, 0xbc, 0xce, 0xc7, 0x92, 0x37, 0x74, 0x83, 0xb1, 0x0c, 0xa1,
	0xad, 0x29, 0x27, 0x53, 0x2e, 0x33, 0x6d, 0x76, 0xbd, 0x52, 0xbf, 0x59, 0x61, 0xa5, 0x3f, 0x41,
	0xf7, 0x38, 0x08, 0xce, 0x8d, 0xa0, 0xd7, 0xb1, 0xde, 0x83, 0x2d, 0x3f, 0x08, 0xc6, 0x41, 0x1a,
	0xaf, 0xc3, 0x32, 0x44, 0xbf, 0x81, 0x5e, 0xc9, 0xbf, 0x8e, 0x2f, 0x0d, 0x81, 0xe4, 0x64, 0xb4,
	0xc7, 0x73, 0x1e, 0x26, 0x9b, 0x09, 0xcd, 0x85, 0xd6, 0x9f, 0x3c, 0x4c, 0xee, 0x0a, 0xc8, 0x61,
	0x49, 0x82, 0x4e, 0x45, 0x82, 0xcf, 0x60, 0x97, 0x61, 0xcc, 0xe7, 0x58, 0x4f, 0xee, 0x31, 0x74,
	0x84, 0xd9, 0x7a, 0x17, 0xfe, 0x6e, 0x81, 0x7e, 0x0b, 0xfd, 0x6a, 0xa0, 0x5a, 0x96, 0x37, 0xd0,
	0x2f, 0xb3, 0x3c, 0xc3, 0xa9, 0xda, 0x90, 0x63, 0x84, 0x53, 0x55, 0xe2, 0x98, 0x41, 0xad, 0xdc,
	0x9b, 0x70, 0x72, 0x83, 0x41, 0xc1, 0xb2, 0xc0, 0xf4, 0x1c, 0xba, 0x69, 0xb2, 0x17, 0x66, 0x65,
	0x93, 0x44, 0xe5, 0x70, 0xf6, 0x52, 0xb8, 0x03, 0x68, 0xe9, 0xa9, 0xac, 0x69, 0x17, 0x7d, 0x01,
	0xed, 0x74, 0xcb, 0x43, 0xc8, 0xfb, 0x00, 0x5a, 0xbf, 0xdc, 0x86, 0xaa, 0x26, 0x5f, 0xba, 0xe5,
	0x21, 0xf2, 0x3d, 0x81, 0x4f, 0x9e, 0xa1, 0x2a, 0x1b, 0x5e, 0x49, 0x14, 0x72, 0x5d, 0xfe, 0x57,
	0xe0, 0xae, 0x76, 0xa9, 0xad, 0xe7, 0x53, 0x68, 0xea, 0xd3, 0x2a, 0xff, 0x09, 0x9b, 0x9e, 0x76,
	0x64, 0xe9, 0x9a, 0xae, 0x64, 0x14, 0x4a, 0xc9, 0xa3, 0xf9, 0xbd, 0x2b, 0xe7, 0x5d, 0x95, 0x1c,
	0x81, 0xbb, 0xda, 0xa5, 0x56, 0x92, 0x67, 0x30, 0x48, 0x55, 0xb2, 0xca, 0x7f, 0xdd, 0x5f, 0xbf,
	0xf2, 0x78, 0x77, 0x61, 0x6f, 0xa9, 0x23, 0x67, 0xa1, 0xd4, 0x33, 0xa4, 0xaf, 0xef, 0xb5, 0x37,
	0xb5, 0xd4, 0xb6, 0xea, 0x0b, 0x68, 0xea, 0xa4, 0x79, 0xab, 0x96, 0x66, 0x97, 0xda, 0xa8, 0x82,
	0x9d, 0x97, 0x8b, 0x64, 0xb2, 0xc1, 0x29, 0xed, 0x42, 0x4b, 0x2a, 0x5f, 0xa8, 0xe2, 0x65, 0x92,
	0x43, 0x7d, 0x37, 0x44, 0x61, 0x1c, 0xa6, 0x97, 0x46, 0x93, 0xa5, 0x40, 0xff, 0x12, 0x3c, 0x0a,
	0x2e, 0xf9, 0x05, 0xfe, 0x65, 0x2e, 0x8d, 0x36, 0x2b, 0x30, 0xfd, 0x1b, 0x76, 0x2b, 0x59, 0x1f,
	0x40, 0x86, 0x95, 0x13, 0xda, 0x59, 0x7b, 0x42, 0xff, 0xac, 0x8f, 0x1f, 0x7d, 0x4b, 0x6d, 0xc0,
	0xba, 0xb8, 0xf7, 0xec, 0xd2, 0xbd, 0x47, 0x9f, 0xc0, 0xa3, 0xa5, 0x08, 0xb5, 0x72, 0xf9, 0x15,
	0x3e, 0x4c, 0xe5, 0x52, 0x71, 0xdc, 0xe4, 0x6c, 0xf9, 0xbc, 0x7c, 0x3d, 0x56, 0x39, 0x69, 0xc3,
	0xd7, 0x3f, 0x42, 0x7f, 0xf9, 0x1d, 0x49, 0x00, 0xb6, 0x2e, 0xb8, 0x88, 0xfd, 0xa8, 0xff, 0x01,
	0xe9, 0x41, 0xe7, 0x52, 0xf8, 0x89, 0x0c, 0x31, 0x51, 0x7d, 0x8b, 0x74, 0xa1, 0x7d, 0xf2, 0x87,
	0xaf, 0x18, 0xe7, 0x71, 0xdf, 0x7e, 0xda, 0xf8, 0xdd, 0x9e, 0x5d, 0x5d, 0x6d, 0x99, 0xf7, 0xea,
	0x77, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x98, 0x03, 0x08, 0x14, 0xe0, 0x0a, 0x00, 0x00,
}
