// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupType int32

const (
	GroupType_Normal    GroupType = 0
	GroupType_Transient GroupType = 1
	GroupType_ChatRoom  GroupType = 2
)

var GroupType_name = map[int32]string{
	0: "Normal",
	1: "Transient",
	2: "ChatRoom",
}

var GroupType_value = map[string]int32{
	"Normal":    0,
	"Transient": 1,
	"ChatRoom":  2,
}

func (x GroupType) String() string {
	return proto.EnumName(GroupType_name, int32(x))
}

func (GroupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{0}
}

type Group struct {
	Type                 GroupType         `protobuf:"varint,1,opt,name=type,proto3,enum=GroupType" json:"type,omitempty"`
	ID                   int64             `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Extra                map[string]string `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	LastMessageID        int64             `protobuf:"varint,4,opt,name=lastMessageID,proto3" json:"lastMessageID,omitempty"`
	LastMessageAt        int64             `protobuf:"varint,5,opt,name=lastMessageAt,proto3" json:"lastMessageAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{0}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetType() GroupType {
	if m != nil {
		return m.Type
	}
	return GroupType_Normal
}

func (m *Group) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Group) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *Group) GetLastMessageID() int64 {
	if m != nil {
		return m.LastMessageID
	}
	return 0
}

func (m *Group) GetLastMessageAt() int64 {
	if m != nil {
		return m.LastMessageAt
	}
	return 0
}

// 创建对话
type CreateGroupReq struct {
	Members              []string          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Extra                map[string]string `protobuf:"bytes,2,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateGroupReq) Reset()         { *m = CreateGroupReq{} }
func (m *CreateGroupReq) String() string { return proto.CompactTextString(m) }
func (*CreateGroupReq) ProtoMessage()    {}
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{1}
}

func (m *CreateGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupReq.Unmarshal(m, b)
}
func (m *CreateGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupReq.Marshal(b, m, deterministic)
}
func (m *CreateGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupReq.Merge(m, src)
}
func (m *CreateGroupReq) XXX_Size() int {
	return xxx_messageInfo_CreateGroupReq.Size(m)
}
func (m *CreateGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupReq proto.InternalMessageInfo

func (m *CreateGroupReq) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *CreateGroupReq) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

type CreateGroupResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Group                *Group   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupResp) Reset()         { *m = CreateGroupResp{} }
func (m *CreateGroupResp) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResp) ProtoMessage()    {}
func (*CreateGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{2}
}

func (m *CreateGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResp.Unmarshal(m, b)
}
func (m *CreateGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResp.Marshal(b, m, deterministic)
}
func (m *CreateGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResp.Merge(m, src)
}
func (m *CreateGroupResp) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResp.Size(m)
}
func (m *CreateGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResp proto.InternalMessageInfo

func (m *CreateGroupResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *CreateGroupResp) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type NotifyInvited struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	InitBy               string   `protobuf:"bytes,2,opt,name=initBy,proto3" json:"initBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyInvited) Reset()         { *m = NotifyInvited{} }
func (m *NotifyInvited) String() string { return proto.CompactTextString(m) }
func (*NotifyInvited) ProtoMessage()    {}
func (*NotifyInvited) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{3}
}

func (m *NotifyInvited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyInvited.Unmarshal(m, b)
}
func (m *NotifyInvited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyInvited.Marshal(b, m, deterministic)
}
func (m *NotifyInvited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyInvited.Merge(m, src)
}
func (m *NotifyInvited) XXX_Size() int {
	return xxx_messageInfo_NotifyInvited.Size(m)
}
func (m *NotifyInvited) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyInvited.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyInvited proto.InternalMessageInfo

func (m *NotifyInvited) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *NotifyInvited) GetInitBy() string {
	if m != nil {
		return m.InitBy
	}
	return ""
}

// 用户发送消息
type Message struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type MessageInfo struct {
	Msg                  *Message `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	CreateAt             int64    `protobuf:"varint,3,opt,name=createAt,proto3" json:"createAt,omitempty"`
	MsgID                int64    `protobuf:"varint,4,opt,name=msgID,proto3" json:"msgID,omitempty"`
	Recalled             bool     `protobuf:"varint,5,opt,name=recalled,proto3" json:"recalled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageInfo) Reset()         { *m = MessageInfo{} }
func (m *MessageInfo) String() string { return proto.CompactTextString(m) }
func (*MessageInfo) ProtoMessage()    {}
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{5}
}

func (m *MessageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageInfo.Unmarshal(m, b)
}
func (m *MessageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageInfo.Marshal(b, m, deterministic)
}
func (m *MessageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageInfo.Merge(m, src)
}
func (m *MessageInfo) XXX_Size() int {
	return xxx_messageInfo_MessageInfo.Size(m)
}
func (m *MessageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MessageInfo proto.InternalMessageInfo

func (m *MessageInfo) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *MessageInfo) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *MessageInfo) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *MessageInfo) GetMsgID() int64 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

func (m *MessageInfo) GetRecalled() bool {
	if m != nil {
		return m.Recalled
	}
	return false
}

type SendMessageReq struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Msg                  *Message `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageReq) Reset()         { *m = SendMessageReq{} }
func (m *SendMessageReq) String() string { return proto.CompactTextString(m) }
func (*SendMessageReq) ProtoMessage()    {}
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{6}
}

func (m *SendMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageReq.Unmarshal(m, b)
}
func (m *SendMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageReq.Marshal(b, m, deterministic)
}
func (m *SendMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageReq.Merge(m, src)
}
func (m *SendMessageReq) XXX_Size() int {
	return xxx_messageInfo_SendMessageReq.Size(m)
}
func (m *SendMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageReq proto.InternalMessageInfo

func (m *SendMessageReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *SendMessageReq) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type SendMessageResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Group                *Group   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResp) Reset()         { *m = SendMessageResp{} }
func (m *SendMessageResp) String() string { return proto.CompactTextString(m) }
func (*SendMessageResp) ProtoMessage()    {}
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{7}
}

func (m *SendMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResp.Unmarshal(m, b)
}
func (m *SendMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResp.Marshal(b, m, deterministic)
}
func (m *SendMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResp.Merge(m, src)
}
func (m *SendMessageResp) XXX_Size() int {
	return xxx_messageInfo_SendMessageResp.Size(m)
}
func (m *SendMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResp proto.InternalMessageInfo

func (m *SendMessageResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *SendMessageResp) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type NotifyMessage struct {
	Group                *Group         `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	MsgInfos             []*MessageInfo `protobuf:"bytes,2,rep,name=msgInfos,proto3" json:"msgInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NotifyMessage) Reset()         { *m = NotifyMessage{} }
func (m *NotifyMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyMessage) ProtoMessage()    {}
func (*NotifyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{8}
}

func (m *NotifyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMessage.Unmarshal(m, b)
}
func (m *NotifyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMessage.Marshal(b, m, deterministic)
}
func (m *NotifyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMessage.Merge(m, src)
}
func (m *NotifyMessage) XXX_Size() int {
	return xxx_messageInfo_NotifyMessage.Size(m)
}
func (m *NotifyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMessage proto.InternalMessageInfo

func (m *NotifyMessage) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *NotifyMessage) GetMsgInfos() []*MessageInfo {
	if m != nil {
		return m.MsgInfos
	}
	return nil
}

type AddMemberReq struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	AddIds               []string `protobuf:"bytes,2,rep,name=addIds,proto3" json:"addIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMemberReq) Reset()         { *m = AddMemberReq{} }
func (m *AddMemberReq) String() string { return proto.CompactTextString(m) }
func (*AddMemberReq) ProtoMessage()    {}
func (*AddMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{9}
}

func (m *AddMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMemberReq.Unmarshal(m, b)
}
func (m *AddMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMemberReq.Marshal(b, m, deterministic)
}
func (m *AddMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMemberReq.Merge(m, src)
}
func (m *AddMemberReq) XXX_Size() int {
	return xxx_messageInfo_AddMemberReq.Size(m)
}
func (m *AddMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddMemberReq proto.InternalMessageInfo

func (m *AddMemberReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *AddMemberReq) GetAddIds() []string {
	if m != nil {
		return m.AddIds
	}
	return nil
}

type AddMemberResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMemberResp) Reset()         { *m = AddMemberResp{} }
func (m *AddMemberResp) String() string { return proto.CompactTextString(m) }
func (*AddMemberResp) ProtoMessage()    {}
func (*AddMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{10}
}

func (m *AddMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMemberResp.Unmarshal(m, b)
}
func (m *AddMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMemberResp.Marshal(b, m, deterministic)
}
func (m *AddMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMemberResp.Merge(m, src)
}
func (m *AddMemberResp) XXX_Size() int {
	return xxx_messageInfo_AddMemberResp.Size(m)
}
func (m *AddMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddMemberResp proto.InternalMessageInfo

func (m *AddMemberResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

type NotifyMemberJoined struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	JoinIds              []string `protobuf:"bytes,2,rep,name=joinIds,proto3" json:"joinIds,omitempty"`
	InitBy               string   `protobuf:"bytes,3,opt,name=initBy,proto3" json:"initBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyMemberJoined) Reset()         { *m = NotifyMemberJoined{} }
func (m *NotifyMemberJoined) String() string { return proto.CompactTextString(m) }
func (*NotifyMemberJoined) ProtoMessage()    {}
func (*NotifyMemberJoined) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{11}
}

func (m *NotifyMemberJoined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMemberJoined.Unmarshal(m, b)
}
func (m *NotifyMemberJoined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMemberJoined.Marshal(b, m, deterministic)
}
func (m *NotifyMemberJoined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMemberJoined.Merge(m, src)
}
func (m *NotifyMemberJoined) XXX_Size() int {
	return xxx_messageInfo_NotifyMemberJoined.Size(m)
}
func (m *NotifyMemberJoined) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMemberJoined.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMemberJoined proto.InternalMessageInfo

func (m *NotifyMemberJoined) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *NotifyMemberJoined) GetJoinIds() []string {
	if m != nil {
		return m.JoinIds
	}
	return nil
}

func (m *NotifyMemberJoined) GetInitBy() string {
	if m != nil {
		return m.InitBy
	}
	return ""
}

type RemoveMemberReq struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	RemoveIds            []string `protobuf:"bytes,2,rep,name=removeIds,proto3" json:"removeIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveMemberReq) Reset()         { *m = RemoveMemberReq{} }
func (m *RemoveMemberReq) String() string { return proto.CompactTextString(m) }
func (*RemoveMemberReq) ProtoMessage()    {}
func (*RemoveMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{12}
}

func (m *RemoveMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMemberReq.Unmarshal(m, b)
}
func (m *RemoveMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMemberReq.Marshal(b, m, deterministic)
}
func (m *RemoveMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMemberReq.Merge(m, src)
}
func (m *RemoveMemberReq) XXX_Size() int {
	return xxx_messageInfo_RemoveMemberReq.Size(m)
}
func (m *RemoveMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMemberReq proto.InternalMessageInfo

func (m *RemoveMemberReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *RemoveMemberReq) GetRemoveIds() []string {
	if m != nil {
		return m.RemoveIds
	}
	return nil
}

type RemoveMemberResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveMemberResp) Reset()         { *m = RemoveMemberResp{} }
func (m *RemoveMemberResp) String() string { return proto.CompactTextString(m) }
func (*RemoveMemberResp) ProtoMessage()    {}
func (*RemoveMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{13}
}

func (m *RemoveMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMemberResp.Unmarshal(m, b)
}
func (m *RemoveMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMemberResp.Marshal(b, m, deterministic)
}
func (m *RemoveMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMemberResp.Merge(m, src)
}
func (m *RemoveMemberResp) XXX_Size() int {
	return xxx_messageInfo_RemoveMemberResp.Size(m)
}
func (m *RemoveMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMemberResp proto.InternalMessageInfo

func (m *RemoveMemberResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

type NotifyMemberLeft struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	LeftIds              []string `protobuf:"bytes,2,rep,name=leftIds,proto3" json:"leftIds,omitempty"`
	KickedBy             string   `protobuf:"bytes,3,opt,name=kickedBy,proto3" json:"kickedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyMemberLeft) Reset()         { *m = NotifyMemberLeft{} }
func (m *NotifyMemberLeft) String() string { return proto.CompactTextString(m) }
func (*NotifyMemberLeft) ProtoMessage()    {}
func (*NotifyMemberLeft) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{14}
}

func (m *NotifyMemberLeft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMemberLeft.Unmarshal(m, b)
}
func (m *NotifyMemberLeft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMemberLeft.Marshal(b, m, deterministic)
}
func (m *NotifyMemberLeft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMemberLeft.Merge(m, src)
}
func (m *NotifyMemberLeft) XXX_Size() int {
	return xxx_messageInfo_NotifyMemberLeft.Size(m)
}
func (m *NotifyMemberLeft) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMemberLeft.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMemberLeft proto.InternalMessageInfo

func (m *NotifyMemberLeft) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *NotifyMemberLeft) GetLeftIds() []string {
	if m != nil {
		return m.LeftIds
	}
	return nil
}

func (m *NotifyMemberLeft) GetKickedBy() string {
	if m != nil {
		return m.KickedBy
	}
	return ""
}

type NotifyKicked struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	KickedBy             string   `protobuf:"bytes,2,opt,name=kickedBy,proto3" json:"kickedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyKicked) Reset()         { *m = NotifyKicked{} }
func (m *NotifyKicked) String() string { return proto.CompactTextString(m) }
func (*NotifyKicked) ProtoMessage()    {}
func (*NotifyKicked) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{15}
}

func (m *NotifyKicked) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyKicked.Unmarshal(m, b)
}
func (m *NotifyKicked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyKicked.Marshal(b, m, deterministic)
}
func (m *NotifyKicked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyKicked.Merge(m, src)
}
func (m *NotifyKicked) XXX_Size() int {
	return xxx_messageInfo_NotifyKicked.Size(m)
}
func (m *NotifyKicked) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyKicked.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyKicked proto.InternalMessageInfo

func (m *NotifyKicked) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *NotifyKicked) GetKickedBy() string {
	if m != nil {
		return m.KickedBy
	}
	return ""
}

type JoinReq struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinReq) Reset()         { *m = JoinReq{} }
func (m *JoinReq) String() string { return proto.CompactTextString(m) }
func (*JoinReq) ProtoMessage()    {}
func (*JoinReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{16}
}

func (m *JoinReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinReq.Unmarshal(m, b)
}
func (m *JoinReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinReq.Marshal(b, m, deterministic)
}
func (m *JoinReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinReq.Merge(m, src)
}
func (m *JoinReq) XXX_Size() int {
	return xxx_messageInfo_JoinReq.Size(m)
}
func (m *JoinReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinReq proto.InternalMessageInfo

func (m *JoinReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

type JoinResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Group                *Group   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResp) Reset()         { *m = JoinResp{} }
func (m *JoinResp) String() string { return proto.CompactTextString(m) }
func (*JoinResp) ProtoMessage()    {}
func (*JoinResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{17}
}

func (m *JoinResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResp.Unmarshal(m, b)
}
func (m *JoinResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResp.Marshal(b, m, deterministic)
}
func (m *JoinResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResp.Merge(m, src)
}
func (m *JoinResp) XXX_Size() int {
	return xxx_messageInfo_JoinResp.Size(m)
}
func (m *JoinResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResp proto.InternalMessageInfo

func (m *JoinResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *JoinResp) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

// 主动
type QuitReq struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitReq) Reset()         { *m = QuitReq{} }
func (m *QuitReq) String() string { return proto.CompactTextString(m) }
func (*QuitReq) ProtoMessage()    {}
func (*QuitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{18}
}

func (m *QuitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitReq.Unmarshal(m, b)
}
func (m *QuitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitReq.Marshal(b, m, deterministic)
}
func (m *QuitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitReq.Merge(m, src)
}
func (m *QuitReq) XXX_Size() int {
	return xxx_messageInfo_QuitReq.Size(m)
}
func (m *QuitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitReq.DiscardUnknown(m)
}

var xxx_messageInfo_QuitReq proto.InternalMessageInfo

func (m *QuitReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

type QuitResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Group                *Group   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitResp) Reset()         { *m = QuitResp{} }
func (m *QuitResp) String() string { return proto.CompactTextString(m) }
func (*QuitResp) ProtoMessage()    {}
func (*QuitResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{19}
}

func (m *QuitResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitResp.Unmarshal(m, b)
}
func (m *QuitResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitResp.Marshal(b, m, deterministic)
}
func (m *QuitResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitResp.Merge(m, src)
}
func (m *QuitResp) XXX_Size() int {
	return xxx_messageInfo_QuitResp.Size(m)
}
func (m *QuitResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitResp.DiscardUnknown(m)
}

var xxx_messageInfo_QuitResp proto.InternalMessageInfo

func (m *QuitResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *QuitResp) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

// 获取会话的成员列表，对于像「聊天室」这样的特殊对话，并不存在「成员列表」属性
type GetGroupUsersReq struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupUsersReq) Reset()         { *m = GetGroupUsersReq{} }
func (m *GetGroupUsersReq) String() string { return proto.CompactTextString(m) }
func (*GetGroupUsersReq) ProtoMessage()    {}
func (*GetGroupUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{20}
}

func (m *GetGroupUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupUsersReq.Unmarshal(m, b)
}
func (m *GetGroupUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupUsersReq.Marshal(b, m, deterministic)
}
func (m *GetGroupUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupUsersReq.Merge(m, src)
}
func (m *GetGroupUsersReq) XXX_Size() int {
	return xxx_messageInfo_GetGroupUsersReq.Size(m)
}
func (m *GetGroupUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupUsersReq proto.InternalMessageInfo

func (m *GetGroupUsersReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

type GetGroupUsersResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupUsersResp) Reset()         { *m = GetGroupUsersResp{} }
func (m *GetGroupUsersResp) String() string { return proto.CompactTextString(m) }
func (*GetGroupUsersResp) ProtoMessage()    {}
func (*GetGroupUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{21}
}

func (m *GetGroupUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupUsersResp.Unmarshal(m, b)
}
func (m *GetGroupUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupUsersResp.Marshal(b, m, deterministic)
}
func (m *GetGroupUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupUsersResp.Merge(m, src)
}
func (m *GetGroupUsersResp) XXX_Size() int {
	return xxx_messageInfo_GetGroupUsersResp.Size(m)
}
func (m *GetGroupUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupUsersResp proto.InternalMessageInfo

func (m *GetGroupUsersResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *GetGroupUsersResp) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// 解散会话
type DissolveGroupReq struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DissolveGroupReq) Reset()         { *m = DissolveGroupReq{} }
func (m *DissolveGroupReq) String() string { return proto.CompactTextString(m) }
func (*DissolveGroupReq) ProtoMessage()    {}
func (*DissolveGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{22}
}

func (m *DissolveGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DissolveGroupReq.Unmarshal(m, b)
}
func (m *DissolveGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DissolveGroupReq.Marshal(b, m, deterministic)
}
func (m *DissolveGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DissolveGroupReq.Merge(m, src)
}
func (m *DissolveGroupReq) XXX_Size() int {
	return xxx_messageInfo_DissolveGroupReq.Size(m)
}
func (m *DissolveGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DissolveGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_DissolveGroupReq proto.InternalMessageInfo

func (m *DissolveGroupReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

type DissolveGroupResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DissolveGroupResp) Reset()         { *m = DissolveGroupResp{} }
func (m *DissolveGroupResp) String() string { return proto.CompactTextString(m) }
func (*DissolveGroupResp) ProtoMessage()    {}
func (*DissolveGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{23}
}

func (m *DissolveGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DissolveGroupResp.Unmarshal(m, b)
}
func (m *DissolveGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DissolveGroupResp.Marshal(b, m, deterministic)
}
func (m *DissolveGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DissolveGroupResp.Merge(m, src)
}
func (m *DissolveGroupResp) XXX_Size() int {
	return xxx_messageInfo_DissolveGroupResp.Size(m)
}
func (m *DissolveGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DissolveGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_DissolveGroupResp proto.InternalMessageInfo

func (m *DissolveGroupResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

type NotifyDissolveGroup struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	InitBy               string   `protobuf:"bytes,2,opt,name=initBy,proto3" json:"initBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyDissolveGroup) Reset()         { *m = NotifyDissolveGroup{} }
func (m *NotifyDissolveGroup) String() string { return proto.CompactTextString(m) }
func (*NotifyDissolveGroup) ProtoMessage()    {}
func (*NotifyDissolveGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{24}
}

func (m *NotifyDissolveGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyDissolveGroup.Unmarshal(m, b)
}
func (m *NotifyDissolveGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyDissolveGroup.Marshal(b, m, deterministic)
}
func (m *NotifyDissolveGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyDissolveGroup.Merge(m, src)
}
func (m *NotifyDissolveGroup) XXX_Size() int {
	return xxx_messageInfo_NotifyDissolveGroup.Size(m)
}
func (m *NotifyDissolveGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyDissolveGroup.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyDissolveGroup proto.InternalMessageInfo

func (m *NotifyDissolveGroup) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *NotifyDissolveGroup) GetInitBy() string {
	if m != nil {
		return m.InitBy
	}
	return ""
}

// 拉取列表
type GetGroupListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupListReq) Reset()         { *m = GetGroupListReq{} }
func (m *GetGroupListReq) String() string { return proto.CompactTextString(m) }
func (*GetGroupListReq) ProtoMessage()    {}
func (*GetGroupListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{25}
}

func (m *GetGroupListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupListReq.Unmarshal(m, b)
}
func (m *GetGroupListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupListReq.Marshal(b, m, deterministic)
}
func (m *GetGroupListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupListReq.Merge(m, src)
}
func (m *GetGroupListReq) XXX_Size() int {
	return xxx_messageInfo_GetGroupListReq.Size(m)
}
func (m *GetGroupListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupListReq proto.InternalMessageInfo

type GetGroupListResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Groups               []*Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupListResp) Reset()         { *m = GetGroupListResp{} }
func (m *GetGroupListResp) String() string { return proto.CompactTextString(m) }
func (*GetGroupListResp) ProtoMessage()    {}
func (*GetGroupListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{26}
}

func (m *GetGroupListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupListResp.Unmarshal(m, b)
}
func (m *GetGroupListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupListResp.Marshal(b, m, deterministic)
}
func (m *GetGroupListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupListResp.Merge(m, src)
}
func (m *GetGroupListResp) XXX_Size() int {
	return xxx_messageInfo_GetGroupListResp.Size(m)
}
func (m *GetGroupListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupListResp proto.InternalMessageInfo

func (m *GetGroupListResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *GetGroupListResp) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

// 会话消息同步
type SyncMessageReq struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	StartID              int64    `protobuf:"varint,2,opt,name=startID,proto3" json:"startID,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	OldToNew             bool     `protobuf:"varint,4,opt,name=oldToNew,proto3" json:"oldToNew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncMessageReq) Reset()         { *m = SyncMessageReq{} }
func (m *SyncMessageReq) String() string { return proto.CompactTextString(m) }
func (*SyncMessageReq) ProtoMessage()    {}
func (*SyncMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{27}
}

func (m *SyncMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessageReq.Unmarshal(m, b)
}
func (m *SyncMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessageReq.Marshal(b, m, deterministic)
}
func (m *SyncMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessageReq.Merge(m, src)
}
func (m *SyncMessageReq) XXX_Size() int {
	return xxx_messageInfo_SyncMessageReq.Size(m)
}
func (m *SyncMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessageReq proto.InternalMessageInfo

func (m *SyncMessageReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *SyncMessageReq) GetStartID() int64 {
	if m != nil {
		return m.StartID
	}
	return 0
}

func (m *SyncMessageReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SyncMessageReq) GetOldToNew() bool {
	if m != nil {
		return m.OldToNew
	}
	return false
}

type SyncMessageResp struct {
	Code                 ErrCode        `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Group                *Group         `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	MsgInfos             []*MessageInfo `protobuf:"bytes,3,rep,name=msgInfos,proto3" json:"msgInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SyncMessageResp) Reset()         { *m = SyncMessageResp{} }
func (m *SyncMessageResp) String() string { return proto.CompactTextString(m) }
func (*SyncMessageResp) ProtoMessage()    {}
func (*SyncMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{28}
}

func (m *SyncMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessageResp.Unmarshal(m, b)
}
func (m *SyncMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessageResp.Marshal(b, m, deterministic)
}
func (m *SyncMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessageResp.Merge(m, src)
}
func (m *SyncMessageResp) XXX_Size() int {
	return xxx_messageInfo_SyncMessageResp.Size(m)
}
func (m *SyncMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessageResp proto.InternalMessageInfo

func (m *SyncMessageResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

func (m *SyncMessageResp) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *SyncMessageResp) GetMsgInfos() []*MessageInfo {
	if m != nil {
		return m.MsgInfos
	}
	return nil
}

type RecallMessageReq struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	MsgID                int64    `protobuf:"varint,2,opt,name=msgID,proto3" json:"msgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecallMessageReq) Reset()         { *m = RecallMessageReq{} }
func (m *RecallMessageReq) String() string { return proto.CompactTextString(m) }
func (*RecallMessageReq) ProtoMessage()    {}
func (*RecallMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{29}
}

func (m *RecallMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecallMessageReq.Unmarshal(m, b)
}
func (m *RecallMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecallMessageReq.Marshal(b, m, deterministic)
}
func (m *RecallMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecallMessageReq.Merge(m, src)
}
func (m *RecallMessageReq) XXX_Size() int {
	return xxx_messageInfo_RecallMessageReq.Size(m)
}
func (m *RecallMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecallMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecallMessageReq proto.InternalMessageInfo

func (m *RecallMessageReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *RecallMessageReq) GetMsgID() int64 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

type RecallMessageResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecallMessageResp) Reset()         { *m = RecallMessageResp{} }
func (m *RecallMessageResp) String() string { return proto.CompactTextString(m) }
func (*RecallMessageResp) ProtoMessage()    {}
func (*RecallMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{30}
}

func (m *RecallMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecallMessageResp.Unmarshal(m, b)
}
func (m *RecallMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecallMessageResp.Marshal(b, m, deterministic)
}
func (m *RecallMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecallMessageResp.Merge(m, src)
}
func (m *RecallMessageResp) XXX_Size() int {
	return xxx_messageInfo_RecallMessageResp.Size(m)
}
func (m *RecallMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RecallMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_RecallMessageResp proto.InternalMessageInfo

func (m *RecallMessageResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

type NotifyRecallMessage struct {
	Group                *Group       `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Msg                  *MessageInfo `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NotifyRecallMessage) Reset()         { *m = NotifyRecallMessage{} }
func (m *NotifyRecallMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyRecallMessage) ProtoMessage()    {}
func (*NotifyRecallMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{31}
}

func (m *NotifyRecallMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRecallMessage.Unmarshal(m, b)
}
func (m *NotifyRecallMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRecallMessage.Marshal(b, m, deterministic)
}
func (m *NotifyRecallMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRecallMessage.Merge(m, src)
}
func (m *NotifyRecallMessage) XXX_Size() int {
	return xxx_messageInfo_NotifyRecallMessage.Size(m)
}
func (m *NotifyRecallMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRecallMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRecallMessage proto.InternalMessageInfo

func (m *NotifyRecallMessage) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *NotifyRecallMessage) GetMsg() *MessageInfo {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterEnum("GroupType", GroupType_name, GroupType_value)
	proto.RegisterType((*Group)(nil), "Group")
	proto.RegisterMapType((map[string]string)(nil), "Group.ExtraEntry")
	proto.RegisterType((*CreateGroupReq)(nil), "CreateGroupReq")
	proto.RegisterMapType((map[string]string)(nil), "CreateGroupReq.ExtraEntry")
	proto.RegisterType((*CreateGroupResp)(nil), "CreateGroupResp")
	proto.RegisterType((*NotifyInvited)(nil), "NotifyInvited")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*MessageInfo)(nil), "MessageInfo")
	proto.RegisterType((*SendMessageReq)(nil), "SendMessageReq")
	proto.RegisterType((*SendMessageResp)(nil), "SendMessageResp")
	proto.RegisterType((*NotifyMessage)(nil), "NotifyMessage")
	proto.RegisterType((*AddMemberReq)(nil), "AddMemberReq")
	proto.RegisterType((*AddMemberResp)(nil), "AddMemberResp")
	proto.RegisterType((*NotifyMemberJoined)(nil), "NotifyMemberJoined")
	proto.RegisterType((*RemoveMemberReq)(nil), "RemoveMemberReq")
	proto.RegisterType((*RemoveMemberResp)(nil), "RemoveMemberResp")
	proto.RegisterType((*NotifyMemberLeft)(nil), "NotifyMemberLeft")
	proto.RegisterType((*NotifyKicked)(nil), "NotifyKicked")
	proto.RegisterType((*JoinReq)(nil), "JoinReq")
	proto.RegisterType((*JoinResp)(nil), "JoinResp")
	proto.RegisterType((*QuitReq)(nil), "QuitReq")
	proto.RegisterType((*QuitResp)(nil), "QuitResp")
	proto.RegisterType((*GetGroupUsersReq)(nil), "GetGroupUsersReq")
	proto.RegisterType((*GetGroupUsersResp)(nil), "GetGroupUsersResp")
	proto.RegisterType((*DissolveGroupReq)(nil), "DissolveGroupReq")
	proto.RegisterType((*DissolveGroupResp)(nil), "DissolveGroupResp")
	proto.RegisterType((*NotifyDissolveGroup)(nil), "NotifyDissolveGroup")
	proto.RegisterType((*GetGroupListReq)(nil), "GetGroupListReq")
	proto.RegisterType((*GetGroupListResp)(nil), "GetGroupListResp")
	proto.RegisterType((*SyncMessageReq)(nil), "SyncMessageReq")
	proto.RegisterType((*SyncMessageResp)(nil), "SyncMessageResp")
	proto.RegisterType((*RecallMessageReq)(nil), "RecallMessageReq")
	proto.RegisterType((*RecallMessageResp)(nil), "RecallMessageResp")
	proto.RegisterType((*NotifyRecallMessage)(nil), "NotifyRecallMessage")
}

func init() { proto.RegisterFile("group.proto", fileDescriptor_e10f4c9b19ad8eee) }

var fileDescriptor_e10f4c9b19ad8eee = []byte{
	// 859 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0xc7, 0x76, 0xfe, 0xd8, 0xd3, 0x26, 0x4d, 0x17, 0x74, 0xb2, 0x42, 0xa9, 0x2a, 0x1f, 0x12,
	0x11, 0x02, 0xeb, 0x28, 0x3c, 0x9c, 0x78, 0xa2, 0x6d, 0x7a, 0x25, 0x70, 0xad, 0x60, 0x5b, 0x84,
	0xc4, 0x9b, 0x1b, 0x6f, 0x8a, 0xa9, 0xed, 0x0d, 0xbb, 0xdb, 0xdc, 0xe5, 0x53, 0xf0, 0xc6, 0x47,
	0xe4, 0x73, 0xa0, 0xdd, 0xf5, 0x3a, 0x76, 0xda, 0x8b, 0x2b, 0xe5, 0xcd, 0x33, 0x9e, 0x9d, 0xdf,
	0xfc, 0x66, 0x7e, 0x9e, 0x35, 0xec, 0xdc, 0x31, 0xfa, 0x30, 0x0f, 0xe7, 0x8c, 0x0a, 0x3a, 0xec,
	0x11, 0xc6, 0xa6, 0x34, 0x26, 0x85, 0x09, 0x0f, 0x9c, 0x30, 0xfd, 0x1c, 0xfc, 0x67, 0x41, 0xfb,
	0x42, 0x86, 0xa2, 0x43, 0x68, 0x89, 0xe5, 0x9c, 0xf8, 0xd6, 0x91, 0x35, 0xea, 0x1f, 0x43, 0xa8,
	0xbc, 0x37, 0xcb, 0x39, 0xc1, 0xca, 0x8f, 0xfa, 0x60, 0x4f, 0xc6, 0xbe, 0x7d, 0x64, 0x8d, 0x1c,
	0x6c, 0x4f, 0xc6, 0xe8, 0x0b, 0x68, 0x93, 0xf7, 0x82, 0x45, 0xbe, 0x73, 0xe4, 0x8c, 0x76, 0x8e,
	0xf7, 0xf5, 0x81, 0xf0, 0x5c, 0xfa, 0xce, 0x73, 0xc1, 0x96, 0x58, 0xbf, 0x47, 0x9f, 0x43, 0x2f,
	0x8d, 0xb8, 0xb8, 0x24, 0x9c, 0x47, 0x77, 0x64, 0x32, 0xf6, 0x5b, 0x2a, 0x47, 0xdd, 0xb9, 0x16,
	0x75, 0x22, 0xfc, 0xf6, 0xa3, 0xa8, 0x13, 0x31, 0x7c, 0x0d, 0xb0, 0x02, 0x40, 0x03, 0x70, 0xee,
	0xc9, 0x52, 0x55, 0xec, 0x61, 0xf9, 0x88, 0x3e, 0x81, 0xf6, 0x22, 0x4a, 0x1f, 0x88, 0xaa, 0xd3,
	0xc3, 0xda, 0xf8, 0xde, 0x7e, 0x6d, 0x05, 0xff, 0x5a, 0xd0, 0x3f, 0x63, 0x24, 0x12, 0x44, 0xd5,
	0x89, 0xc9, 0xdf, 0xc8, 0x87, 0x6e, 0x46, 0xb2, 0x5b, 0xc2, 0xb8, 0x6f, 0x1d, 0x39, 0x23, 0x0f,
	0x1b, 0x13, 0xbd, 0x32, 0xdc, 0x6c, 0xc5, 0x6d, 0x18, 0xd6, 0x4f, 0x3e, 0x26, 0xb9, 0x45, 0x61,
	0x97, 0xb0, 0x57, 0xcb, 0xce, 0xe7, 0xe8, 0x00, 0x5a, 0x72, 0x5c, 0xc5, 0x28, 0xdc, 0xf0, 0x9c,
	0xb1, 0x33, 0x1a, 0x13, 0xac, 0xbc, 0xe8, 0x00, 0xda, 0x6a, 0xb8, 0x2a, 0xd5, 0xce, 0x71, 0x47,
	0x37, 0x1e, 0x6b, 0x67, 0x70, 0x0e, 0xbd, 0x2b, 0x2a, 0x92, 0xd9, 0x72, 0x92, 0x2f, 0x12, 0x41,
	0xe2, 0x55, 0xb8, 0xf5, 0x44, 0x38, 0x7a, 0x01, 0x9d, 0x24, 0x4f, 0xc4, 0xe9, 0xb2, 0x28, 0xac,
	0xb0, 0x82, 0xcf, 0xa0, 0x5b, 0x74, 0x1d, 0x21, 0x68, 0x09, 0xf2, 0x5e, 0x14, 0x6c, 0xd4, 0x73,
	0xf0, 0x8f, 0x05, 0x3b, 0x66, 0x76, 0xf9, 0x8c, 0xa2, 0x21, 0x38, 0x19, 0xbf, 0x2b, 0x20, 0xdc,
	0xb0, 0x78, 0x85, 0xa5, 0x53, 0x42, 0x48, 0xc1, 0x15, 0xe2, 0xf1, 0x70, 0x61, 0xa1, 0x21, 0xb8,
	0x53, 0x45, 0xfc, 0x44, 0xf8, 0x8e, 0x1a, 0x76, 0x69, 0xcb, 0x76, 0x65, 0xfc, 0xae, 0xd4, 0x8a,
	0x36, 0xe4, 0x09, 0x46, 0xa6, 0x51, 0x9a, 0x92, 0x58, 0xc9, 0xc3, 0xc5, 0xa5, 0x1d, 0xbc, 0x81,
	0xfe, 0x35, 0xc9, 0x63, 0x83, 0xac, 0xc7, 0xab, 0x38, 0x4e, 0xc6, 0xaa, 0x2e, 0x07, 0x1b, 0xd3,
	0x54, 0x6b, 0x3f, 0x51, 0xad, 0x1c, 0x47, 0x2d, 0xcf, 0x96, 0xe3, 0xf8, 0xdd, 0x8c, 0xc3, 0x74,
	0x73, 0xf3, 0x38, 0x46, 0xe0, 0x4a, 0xaa, 0xf9, 0x8c, 0xf2, 0x42, 0x7b, 0xbb, 0x61, 0xa5, 0xcf,
	0xb8, 0x7c, 0x1b, 0xfc, 0x00, 0xbb, 0x27, 0x71, 0x7c, 0xa9, 0x04, 0xbb, 0x99, 0xed, 0x0b, 0xe8,
	0x44, 0x71, 0x3c, 0x89, 0x75, 0x46, 0x0f, 0x17, 0x56, 0xf0, 0x35, 0xf4, 0x2a, 0x19, 0x9a, 0x78,
	0x06, 0x31, 0x20, 0xc3, 0x44, 0x9e, 0xf8, 0x89, 0x26, 0x79, 0xa3, 0xba, 0x7c, 0xe8, 0xfe, 0x45,
	0x93, 0x7c, 0x85, 0x6d, 0xcc, 0x8a, 0xee, 0x9c, 0x9a, 0xee, 0x26, 0xb0, 0x87, 0x49, 0x46, 0x17,
	0xe4, 0x39, 0xcc, 0x0e, 0xc0, 0x63, 0x2a, 0x78, 0x05, 0xb0, 0x72, 0x04, 0xaf, 0x60, 0x50, 0x4f,
	0xd5, 0x48, 0x71, 0x06, 0x83, 0x2a, 0xc5, 0xb7, 0x64, 0x26, 0x9a, 0x09, 0xa6, 0x64, 0x26, 0x2a,
	0x04, 0x0b, 0x53, 0x6a, 0xf5, 0x3e, 0x99, 0xde, 0x93, 0xb8, 0xa4, 0x58, 0xda, 0xc1, 0x8f, 0xb0,
	0xab, 0x71, 0x7e, 0x56, 0x9e, 0x06, 0x8c, 0x6a, 0x26, 0x7b, 0x2d, 0xd3, 0x4b, 0xe8, 0xca, 0x41,
	0x6c, 0x6c, 0x53, 0xf0, 0x06, 0x5c, 0x1d, 0xb4, 0xa5, 0x96, 0x5f, 0x42, 0xf7, 0xd7, 0x87, 0x44,
	0x34, 0x82, 0xe9, 0xa0, 0x2d, 0xc1, 0xbe, 0x82, 0xc1, 0x05, 0x11, 0xca, 0xf5, 0x1b, 0x27, 0x8c,
	0x6f, 0x46, 0xbd, 0x82, 0xfd, 0xb5, 0xe8, 0x46, 0xf8, 0x4f, 0xa1, 0x2d, 0x17, 0x91, 0xf9, 0xce,
	0xda, 0xa1, 0x3c, 0x88, 0xb5, 0x4f, 0xa2, 0x8f, 0x13, 0xce, 0x69, 0xba, 0xa8, 0x5d, 0x17, 0x1f,
	0x40, 0xff, 0x06, 0xf6, 0xd7, 0xa2, 0x1b, 0xa5, 0x76, 0x01, 0x1f, 0x6b, 0x09, 0xd4, 0x0e, 0x6e,
	0xfe, 0x8a, 0x9f, 0x5c, 0xd4, 0xfb, 0xb0, 0x67, 0x98, 0xbf, 0x4d, 0xb8, 0x1c, 0x4e, 0xf0, 0xcb,
	0xaa, 0x75, 0xda, 0xd5, 0xd8, 0x8b, 0x43, 0xe8, 0x28, 0x1c, 0xd3, 0x0c, 0x33, 0x8b, 0xc2, 0x1b,
	0x2c, 0xa0, 0x7f, 0xbd, 0xcc, 0xa7, 0xcf, 0x5a, 0xae, 0x3e, 0x74, 0xb9, 0x88, 0x98, 0x28, 0x7f,
	0x16, 0x8c, 0x29, 0x97, 0x7a, 0x9a, 0x64, 0x89, 0xde, 0xf6, 0x6d, 0xac, 0x0d, 0x29, 0x6f, 0x9a,
	0xc6, 0x37, 0xf4, 0x8a, 0xbc, 0x53, 0xdb, 0xde, 0xc5, 0xa5, 0x1d, 0xbc, 0x83, 0xbd, 0x1a, 0xee,
	0x76, 0x9a, 0xaa, 0x6d, 0x57, 0x67, 0xe3, 0x76, 0x3d, 0x95, 0xbb, 0x43, 0xde, 0x2c, 0xcf, 0xa2,
	0x5c, 0xde, 0x56, 0x76, 0xe5, 0xb6, 0x92, 0xaa, 0x58, 0xcb, 0xd1, 0xa8, 0x8a, 0x6b, 0xa3, 0x8a,
	0xda, 0xc1, 0x86, 0xfd, 0x70, 0x58, 0xbd, 0xcd, 0xea, 0x84, 0xe4, 0x8b, 0x2f, 0xbf, 0x03, 0xaf,
	0xfc, 0x97, 0x43, 0x00, 0x9d, 0x2b, 0xca, 0xb2, 0x28, 0x1d, 0x7c, 0x84, 0x7a, 0xe0, 0xdd, 0xb0,
	0x28, 0xe7, 0x09, 0xc9, 0xc5, 0xc0, 0x42, 0xbb, 0xe0, 0x9e, 0xfd, 0x19, 0x09, 0x4c, 0x69, 0x36,
	0xb0, 0x4f, 0x5b, 0x7f, 0xd8, 0xf3, 0xdb, 0xdb, 0x8e, 0xfa, 0x4b, 0xfc, 0xf6, 0xff, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf9, 0x58, 0x19, 0x53, 0x4f, 0x0a, 0x00, 0x00,
}
