// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserState int32

const (
	UserState_OnLine  UserState = 0
	UserState_OffLine UserState = 1
)

var UserState_name = map[int32]string{
	0: "OnLine",
	1: "OffLine",
}

var UserState_value = map[string]int32{
	"OnLine":  0,
	"OffLine": 1,
}

func (x UserState) String() string {
	return proto.EnumName(UserState_name, int32(x))
}

func (UserState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type UserLoginReq struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginReq) Reset()         { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()    {}
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginReq.Unmarshal(m, b)
}
func (m *UserLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginReq.Marshal(b, m, deterministic)
}
func (m *UserLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginReq.Merge(m, src)
}
func (m *UserLoginReq) XXX_Size() int {
	return xxx_messageInfo_UserLoginReq.Size(m)
}
func (m *UserLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginReq proto.InternalMessageInfo

func (m *UserLoginReq) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UserLoginResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResp) Reset()         { *m = UserLoginResp{} }
func (m *UserLoginResp) String() string { return proto.CompactTextString(m) }
func (*UserLoginResp) ProtoMessage()    {}
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserLoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResp.Unmarshal(m, b)
}
func (m *UserLoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResp.Marshal(b, m, deterministic)
}
func (m *UserLoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResp.Merge(m, src)
}
func (m *UserLoginResp) XXX_Size() int {
	return xxx_messageInfo_UserLoginResp.Size(m)
}
func (m *UserLoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResp proto.InternalMessageInfo

func (m *UserLoginResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

type User struct {
	State                UserState         `protobuf:"varint,1,opt,name=state,proto3,enum=UserState" json:"state,omitempty"`
	UserID               string            `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Attr                 map[string]string `protobuf:"bytes,3,rep,name=attr,proto3" json:"attr,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetState() UserState {
	if m != nil {
		return m.State
	}
	return UserState_OnLine
}

func (m *User) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *User) GetAttr() map[string]string {
	if m != nil {
		return m.Attr
	}
	return nil
}

func init() {
	proto.RegisterEnum("UserState", UserState_name, UserState_value)
	proto.RegisterType((*UserLoginReq)(nil), "UserLoginReq")
	proto.RegisterType((*UserLoginResp)(nil), "UserLoginResp")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterMapType((map[string]string)(nil), "User.AttrEntry")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0x4d, 0xda, 0x55, 0xfb, 0xe6, 0xe6, 0x08, 0x22, 0x65, 0x88, 0x94, 0xea, 0x61, 0x08,
	0xf6, 0x30, 0x0f, 0x8a, 0x37, 0xb5, 0x3b, 0x14, 0x06, 0x83, 0x88, 0x17, 0x6f, 0x9d, 0xcb, 0x64,
	0x28, 0x4d, 0xfd, 0x37, 0x13, 0xf6, 0x65, 0xfc, 0xac, 0x92, 0xb4, 0x96, 0xdd, 0xf2, 0x7e, 0xef,
	0xbd, 0xe4, 0x11, 0x60, 0x5b, 0x2b, 0x4a, 0x2b, 0xd2, 0x46, 0x8f, 0x07, 0x8a, 0xe8, 0x5d, 0xaf,
	0x54, 0x23, 0x93, 0x0b, 0x1c, 0xbf, 0xd6, 0x8a, 0xe6, 0xfa, 0x63, 0x53, 0x4a, 0xf5, 0x2d, 0x86,
	0xe0, 0x79, 0x16, 0xb1, 0x98, 0x4d, 0x42, 0xc9, 0xf3, 0x2c, 0xb9, 0xc1, 0x60, 0xcf, 0xaf, 0x2b,
	0x71, 0x0e, 0xdf, 0xd6, 0x5d, 0x64, 0x38, 0x3d, 0x4a, 0x67, 0x44, 0xcf, 0x7a, 0xa5, 0xa4, 0xa3,
	0xc9, 0x2f, 0x83, 0x6f, 0xf3, 0x22, 0x46, 0xaf, 0x36, 0x85, 0xf9, 0xcf, 0x21, 0xb5, 0xf4, 0xc5,
	0x12, 0xd9, 0x18, 0xe2, 0x0c, 0x81, 0x9d, 0x95, 0x67, 0x11, 0x77, 0xaf, 0xb5, 0x4a, 0x5c, 0xc2,
	0x2f, 0x8c, 0xa1, 0xc8, 0x8b, 0xbd, 0x49, 0x7f, 0x7a, 0xe2, 0x8a, 0xe9, 0xa3, 0x31, 0x34, 0x2b,
	0x0d, 0xed, 0xa4, 0x33, 0xc7, 0x77, 0x08, 0x3b, 0x24, 0x46, 0xf0, 0x3e, 0xd5, 0xae, 0x1d, 0x6d,
	0x8f, 0xe2, 0x14, 0xbd, 0x9f, 0xe2, 0x6b, 0xab, 0xda, 0xab, 0x1b, 0xf1, 0xc0, 0xef, 0xd9, 0xf5,
	0x15, 0xc2, 0x6e, 0x89, 0x00, 0x82, 0x45, 0x39, 0xdf, 0x94, 0x6a, 0x74, 0x20, 0xfa, 0x38, 0x5c,
	0xac, 0xd7, 0x4e, 0xb0, 0x27, 0xff, 0x8d, 0x57, 0xcb, 0x65, 0xe0, 0xbe, 0xe8, 0xf6, 0x2f, 0x00,
	0x00, 0xff, 0xff, 0x4d, 0x7b, 0x70, 0xfa, 0x3f, 0x01, 0x00, 0x00,
}
