// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Conversation struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation) Reset()         { *m = Conversation{} }
func (m *Conversation) String() string { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()    {}
func (*Conversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Conversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation.Unmarshal(m, b)
}
func (m *Conversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation.Marshal(b, m, deterministic)
}
func (m *Conversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation.Merge(m, src)
}
func (m *Conversation) XXX_Size() int {
	return xxx_messageInfo_Conversation.Size(m)
}
func (m *Conversation) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation proto.InternalMessageInfo

func (m *Conversation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 创建对话
type CreateConversation struct {
	Members              []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unique               bool     `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConversation) Reset()         { *m = CreateConversation{} }
func (m *CreateConversation) String() string { return proto.CompactTextString(m) }
func (*CreateConversation) ProtoMessage()    {}
func (*CreateConversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *CreateConversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversation.Unmarshal(m, b)
}
func (m *CreateConversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversation.Marshal(b, m, deterministic)
}
func (m *CreateConversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversation.Merge(m, src)
}
func (m *CreateConversation) XXX_Size() int {
	return xxx_messageInfo_CreateConversation.Size(m)
}
func (m *CreateConversation) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversation.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversation proto.InternalMessageInfo

func (m *CreateConversation) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *CreateConversation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateConversation) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

// 发送消息
type Message struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// 收到邀请
type NotifyInvited struct {
	Conv                 *Conversation `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	InitBy               string        `protobuf:"bytes,2,opt,name=initBy,proto3" json:"initBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NotifyInvited) Reset()         { *m = NotifyInvited{} }
func (m *NotifyInvited) String() string { return proto.CompactTextString(m) }
func (*NotifyInvited) ProtoMessage()    {}
func (*NotifyInvited) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *NotifyInvited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyInvited.Unmarshal(m, b)
}
func (m *NotifyInvited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyInvited.Marshal(b, m, deterministic)
}
func (m *NotifyInvited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyInvited.Merge(m, src)
}
func (m *NotifyInvited) XXX_Size() int {
	return xxx_messageInfo_NotifyInvited.Size(m)
}
func (m *NotifyInvited) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyInvited.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyInvited proto.InternalMessageInfo

func (m *NotifyInvited) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

func (m *NotifyInvited) GetInitBy() string {
	if m != nil {
		return m.InitBy
	}
	return ""
}

// 收到聊天信息
type NotifyMessage struct {
	Conv                 *Conversation `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	Msg                  *Message      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NotifyMessage) Reset()         { *m = NotifyMessage{} }
func (m *NotifyMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyMessage) ProtoMessage()    {}
func (*NotifyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *NotifyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMessage.Unmarshal(m, b)
}
func (m *NotifyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMessage.Marshal(b, m, deterministic)
}
func (m *NotifyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMessage.Merge(m, src)
}
func (m *NotifyMessage) XXX_Size() int {
	return xxx_messageInfo_NotifyMessage.Size(m)
}
func (m *NotifyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMessage proto.InternalMessageInfo

func (m *NotifyMessage) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

func (m *NotifyMessage) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*Conversation)(nil), "Conversation")
	proto.RegisterType((*CreateConversation)(nil), "CreateConversation")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*NotifyInvited)(nil), "NotifyInvited")
	proto.RegisterType((*NotifyMessage)(nil), "NotifyMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x15, 0x52, 0xb5, 0xe9, 0x95, 0x2c, 0x1e, 0x90, 0x85, 0x84, 0x14, 0x3c, 0x65, 0xca,
	0x50, 0xbe, 0x41, 0x3b, 0x81, 0x44, 0x07, 0x8f, 0xdd, 0xdc, 0x72, 0x54, 0x96, 0xb0, 0x0d, 0xf6,
	0x35, 0x22, 0xdf, 0x1e, 0xd9, 0xd8, 0xfc, 0xd9, 0xba, 0xbd, 0x67, 0xdf, 0xfd, 0xde, 0xd3, 0x41,
	0x6b, 0x30, 0x04, 0x75, 0xc2, 0xe1, 0xdd, 0x3b, 0x72, 0x42, 0xc0, 0xf5, 0xd6, 0xd9, 0x11, 0x7d,
	0x50, 0xa4, 0x9d, 0x65, 0x0c, 0x66, 0x56, 0x19, 0xe4, 0x55, 0x57, 0xf5, 0x4b, 0x99, 0xb4, 0xd8,
	0x03, 0xdb, 0x7a, 0x54, 0x84, 0xff, 0x26, 0x39, 0x2c, 0x0c, 0x9a, 0x03, 0xfa, 0xc0, 0xab, 0xae,
	0xee, 0x97, 0xb2, 0xd8, 0x1f, 0xc6, 0xd5, 0x2f, 0x83, 0xdd, 0xc0, 0xfc, 0x6c, 0xf5, 0xc7, 0x19,
	0x79, 0xdd, 0x55, 0x7d, 0x23, 0xb3, 0x13, 0x77, 0xb0, 0x78, 0xfe, 0x2e, 0x14, 0xd7, 0x08, 0x3f,
	0xa9, 0x44, 0x47, 0x2d, 0x9e, 0xa0, 0xdd, 0x39, 0xd2, 0xaf, 0xd3, 0xa3, 0x1d, 0x35, 0xe1, 0x0b,
	0xbb, 0x87, 0xd9, 0xd1, 0xd9, 0x31, 0x0d, 0xad, 0xd6, 0xed, 0xf0, 0xb7, 0x92, 0x4c, 0x5f, 0x31,
	0x4a, 0x5b, 0x4d, 0x9b, 0x29, 0x17, 0xc8, 0x4e, 0xec, 0x0a, 0xab, 0x04, 0x5e, 0xc0, 0xba, 0x85,
	0xda, 0x84, 0x53, 0x02, 0xad, 0xd6, 0xcd, 0x90, 0x37, 0x65, 0x7c, 0xdc, 0xc0, 0xbe, 0x49, 0x37,
	0x3c, 0xba, 0xb7, 0xc3, 0x3c, 0xa9, 0x87, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0xa6, 0xf6,
	0x28, 0x5e, 0x01, 0x00, 0x00,
}
