Address           = "127.0.0.1:43210"
MaxBackups        = 3                # 聊天记录保留的表数量
MaxMessageCount   = 200              # 每个会话最大消息缓存

[DBConfig]
SqlType               = "postgres"
Host                  = "localhost"
Port                  = 5432
User		          = "dbuser"
Password              = "123456"
Database              = "yidongdeng"

[LogConfig]
Path            = "log"
Filename        = "im"
MaxSize         = 100    # M
Debug           = true
EnableStdout    = true