// Code generated by protoc-gen-go. DO NOT EDIT.
// source: friend.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FriendStatus int32

const (
	FriendStatus_Agree FriendStatus = 0
	FriendStatus_Apply FriendStatus = 1
)

var FriendStatus_name = map[int32]string{
	0: "Agree",
	1: "Apply",
}

var FriendStatus_value = map[string]int32{
	"Agree": 0,
	"Apply": 1,
}

func (x FriendStatus) String() string {
	return proto.EnumName(FriendStatus_name, int32(x))
}

func (FriendStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{0}
}

type Friend struct {
	Status               FriendStatus `protobuf:"varint,1,opt,name=status,proto3,enum=FriendStatus" json:"status,omitempty"`
	UserID               string       `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Friend) Reset()         { *m = Friend{} }
func (m *Friend) String() string { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()    {}
func (*Friend) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{0}
}

func (m *Friend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friend.Unmarshal(m, b)
}
func (m *Friend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friend.Marshal(b, m, deterministic)
}
func (m *Friend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friend.Merge(m, src)
}
func (m *Friend) XXX_Size() int {
	return xxx_messageInfo_Friend.Size(m)
}
func (m *Friend) XXX_DiscardUnknown() {
	xxx_messageInfo_Friend.DiscardUnknown(m)
}

var xxx_messageInfo_Friend proto.InternalMessageInfo

func (m *Friend) GetStatus() FriendStatus {
	if m != nil {
		return m.Status
	}
	return FriendStatus_Agree
}

func (m *Friend) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type AddFriendReq struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendReq) Reset()         { *m = AddFriendReq{} }
func (m *AddFriendReq) String() string { return proto.CompactTextString(m) }
func (*AddFriendReq) ProtoMessage()    {}
func (*AddFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{1}
}

func (m *AddFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendReq.Unmarshal(m, b)
}
func (m *AddFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendReq.Marshal(b, m, deterministic)
}
func (m *AddFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendReq.Merge(m, src)
}
func (m *AddFriendReq) XXX_Size() int {
	return xxx_messageInfo_AddFriendReq.Size(m)
}
func (m *AddFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendReq proto.InternalMessageInfo

func (m *AddFriendReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type AddFriendResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendResp) Reset()         { *m = AddFriendResp{} }
func (m *AddFriendResp) String() string { return proto.CompactTextString(m) }
func (*AddFriendResp) ProtoMessage()    {}
func (*AddFriendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{2}
}

func (m *AddFriendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendResp.Unmarshal(m, b)
}
func (m *AddFriendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendResp.Marshal(b, m, deterministic)
}
func (m *AddFriendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendResp.Merge(m, src)
}
func (m *AddFriendResp) XXX_Size() int {
	return xxx_messageInfo_AddFriendResp.Size(m)
}
func (m *AddFriendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendResp proto.InternalMessageInfo

func (m *AddFriendResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

type NotifyAddFriend struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyAddFriend) Reset()         { *m = NotifyAddFriend{} }
func (m *NotifyAddFriend) String() string { return proto.CompactTextString(m) }
func (*NotifyAddFriend) ProtoMessage()    {}
func (*NotifyAddFriend) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{3}
}

func (m *NotifyAddFriend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyAddFriend.Unmarshal(m, b)
}
func (m *NotifyAddFriend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyAddFriend.Marshal(b, m, deterministic)
}
func (m *NotifyAddFriend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyAddFriend.Merge(m, src)
}
func (m *NotifyAddFriend) XXX_Size() int {
	return xxx_messageInfo_NotifyAddFriend.Size(m)
}
func (m *NotifyAddFriend) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyAddFriend.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyAddFriend proto.InternalMessageInfo

func (m *NotifyAddFriend) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type AgreeFriendReq struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Agree                bool     `protobuf:"varint,2,opt,name=agree,proto3" json:"agree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgreeFriendReq) Reset()         { *m = AgreeFriendReq{} }
func (m *AgreeFriendReq) String() string { return proto.CompactTextString(m) }
func (*AgreeFriendReq) ProtoMessage()    {}
func (*AgreeFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{4}
}

func (m *AgreeFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgreeFriendReq.Unmarshal(m, b)
}
func (m *AgreeFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgreeFriendReq.Marshal(b, m, deterministic)
}
func (m *AgreeFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreeFriendReq.Merge(m, src)
}
func (m *AgreeFriendReq) XXX_Size() int {
	return xxx_messageInfo_AgreeFriendReq.Size(m)
}
func (m *AgreeFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreeFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_AgreeFriendReq proto.InternalMessageInfo

func (m *AgreeFriendReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AgreeFriendReq) GetAgree() bool {
	if m != nil {
		return m.Agree
	}
	return false
}

type AgreeFriendResp struct {
	Code                 ErrCode  `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgreeFriendResp) Reset()         { *m = AgreeFriendResp{} }
func (m *AgreeFriendResp) String() string { return proto.CompactTextString(m) }
func (*AgreeFriendResp) ProtoMessage()    {}
func (*AgreeFriendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{5}
}

func (m *AgreeFriendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgreeFriendResp.Unmarshal(m, b)
}
func (m *AgreeFriendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgreeFriendResp.Marshal(b, m, deterministic)
}
func (m *AgreeFriendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreeFriendResp.Merge(m, src)
}
func (m *AgreeFriendResp) XXX_Size() int {
	return xxx_messageInfo_AgreeFriendResp.Size(m)
}
func (m *AgreeFriendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreeFriendResp.DiscardUnknown(m)
}

var xxx_messageInfo_AgreeFriendResp proto.InternalMessageInfo

func (m *AgreeFriendResp) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_OK
}

type NotifyAgreeFriend struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Agree                bool     `protobuf:"varint,2,opt,name=agree,proto3" json:"agree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyAgreeFriend) Reset()         { *m = NotifyAgreeFriend{} }
func (m *NotifyAgreeFriend) String() string { return proto.CompactTextString(m) }
func (*NotifyAgreeFriend) ProtoMessage()    {}
func (*NotifyAgreeFriend) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{6}
}

func (m *NotifyAgreeFriend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyAgreeFriend.Unmarshal(m, b)
}
func (m *NotifyAgreeFriend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyAgreeFriend.Marshal(b, m, deterministic)
}
func (m *NotifyAgreeFriend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyAgreeFriend.Merge(m, src)
}
func (m *NotifyAgreeFriend) XXX_Size() int {
	return xxx_messageInfo_NotifyAgreeFriend.Size(m)
}
func (m *NotifyAgreeFriend) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyAgreeFriend.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyAgreeFriend proto.InternalMessageInfo

func (m *NotifyAgreeFriend) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *NotifyAgreeFriend) GetAgree() bool {
	if m != nil {
		return m.Agree
	}
	return false
}

type GetFriendsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendsReq) Reset()         { *m = GetFriendsReq{} }
func (m *GetFriendsReq) String() string { return proto.CompactTextString(m) }
func (*GetFriendsReq) ProtoMessage()    {}
func (*GetFriendsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{7}
}

func (m *GetFriendsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendsReq.Unmarshal(m, b)
}
func (m *GetFriendsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendsReq.Marshal(b, m, deterministic)
}
func (m *GetFriendsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendsReq.Merge(m, src)
}
func (m *GetFriendsReq) XXX_Size() int {
	return xxx_messageInfo_GetFriendsReq.Size(m)
}
func (m *GetFriendsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendsReq proto.InternalMessageInfo

type GetFriendsResp struct {
	Friends              []*Friend `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetFriendsResp) Reset()         { *m = GetFriendsResp{} }
func (m *GetFriendsResp) String() string { return proto.CompactTextString(m) }
func (*GetFriendsResp) ProtoMessage()    {}
func (*GetFriendsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{8}
}

func (m *GetFriendsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendsResp.Unmarshal(m, b)
}
func (m *GetFriendsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendsResp.Marshal(b, m, deterministic)
}
func (m *GetFriendsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendsResp.Merge(m, src)
}
func (m *GetFriendsResp) XXX_Size() int {
	return xxx_messageInfo_GetFriendsResp.Size(m)
}
func (m *GetFriendsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendsResp proto.InternalMessageInfo

func (m *GetFriendsResp) GetFriends() []*Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

func init() {
	proto.RegisterEnum("FriendStatus", FriendStatus_name, FriendStatus_value)
	proto.RegisterType((*Friend)(nil), "Friend")
	proto.RegisterType((*AddFriendReq)(nil), "AddFriendReq")
	proto.RegisterType((*AddFriendResp)(nil), "AddFriendResp")
	proto.RegisterType((*NotifyAddFriend)(nil), "NotifyAddFriend")
	proto.RegisterType((*AgreeFriendReq)(nil), "AgreeFriendReq")
	proto.RegisterType((*AgreeFriendResp)(nil), "AgreeFriendResp")
	proto.RegisterType((*NotifyAgreeFriend)(nil), "NotifyAgreeFriend")
	proto.RegisterType((*GetFriendsReq)(nil), "GetFriendsReq")
	proto.RegisterType((*GetFriendsResp)(nil), "GetFriendsResp")
}

func init() { proto.RegisterFile("friend.proto", fileDescriptor_2b65cbc293af6bbd) }

var fileDescriptor_2b65cbc293af6bbd = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0x36, 0x73, 0xeb, 0xb6, 0xd7, 0x7e, 0xcc, 0x20, 0x32, 0xc4, 0xc3, 0x0c, 0x2a, 0x55, 0xb0,
	0xc2, 0x76, 0x17, 0xea, 0xd7, 0xf0, 0xe2, 0x21, 0xde, 0xbc, 0x6d, 0xe6, 0x9d, 0x0c, 0xc4, 0x64,
	0x49, 0x76, 0xd8, 0xbf, 0x97, 0x26, 0x51, 0xbb, 0x83, 0x14, 0x6f, 0x7d, 0xbe, 0xfa, 0x3e, 0xe1,
	0x81, 0x78, 0xa1, 0x97, 0xf8, 0x29, 0x0a, 0xa5, 0xa5, 0x95, 0x47, 0x09, 0x6a, 0xfd, 0x26, 0x05,
	0x7a, 0xc8, 0xa6, 0x10, 0x3d, 0x3a, 0x99, 0x9e, 0x41, 0x64, 0xec, 0xcc, 0xae, 0xcd, 0x90, 0x8c,
	0x48, 0x9e, 0x8e, 0x93, 0xc2, 0x0b, 0x2f, 0x8e, 0xe4, 0x41, 0xa4, 0x87, 0x10, 0xad, 0x0d, 0xea,
	0xa7, 0xfb, 0x61, 0x6b, 0x44, 0xf2, 0x3e, 0x0f, 0x88, 0x9d, 0x43, 0x5c, 0x0a, 0xe1, 0x23, 0x1c,
	0x57, 0x35, 0x1f, 0xd9, 0xf2, 0x5d, 0x41, 0x52, 0xf3, 0x19, 0x45, 0x8f, 0xa1, 0x5d, 0xf5, 0x09,
	0x57, 0x7b, 0xc5, 0x83, 0xd6, 0x77, 0x52, 0x20, 0x77, 0x2c, 0xbb, 0x80, 0xec, 0x59, 0xda, 0xe5,
	0x62, 0xf3, 0x13, 0xfa, 0xf3, 0xcf, 0x37, 0x90, 0x96, 0xef, 0x1a, 0xb1, 0xb1, 0x03, 0x3d, 0x80,
	0xce, 0xac, 0x72, 0xba, 0x27, 0xf4, 0xb8, 0x07, 0xec, 0x1a, 0xb2, 0xad, 0x7c, 0x63, 0xb7, 0x12,
	0xf6, 0x43, 0xb7, 0xdf, 0xd8, 0x3f, 0x6f, 0x66, 0x90, 0x4c, 0xd1, 0xfa, 0xa8, 0xe1, 0xb8, 0x62,
	0x13, 0x48, 0xeb, 0x84, 0x51, 0xf4, 0x04, 0xba, 0x7e, 0xc0, 0x6a, 0x98, 0xdd, 0x7c, 0x6f, 0xdc,
	0x0d, 0xc3, 0xf0, 0x6f, 0xfe, 0xf2, 0x14, 0xe2, 0xfa, 0x56, 0xb4, 0x0f, 0x1d, 0x57, 0x69, 0xb0,
	0xe3, 0x3e, 0x95, 0xfa, 0xd8, 0x0c, 0xc8, 0x6d, 0xfb, 0xb5, 0xa5, 0xe6, 0xf3, 0xc8, 0xed, 0x3e,
	0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xb1, 0x9e, 0x27, 0x16, 0x02, 0x00, 0x00,
}
