// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Conversation struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation) Reset()         { *m = Conversation{} }
func (m *Conversation) String() string { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()    {}
func (*Conversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Conversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation.Unmarshal(m, b)
}
func (m *Conversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation.Marshal(b, m, deterministic)
}
func (m *Conversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation.Merge(m, src)
}
func (m *Conversation) XXX_Size() int {
	return xxx_messageInfo_Conversation.Size(m)
}
func (m *Conversation) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation proto.InternalMessageInfo

func (m *Conversation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 创建对话
type CreateConversationReq struct {
	Members              []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unique               bool     `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConversationReq) Reset()         { *m = CreateConversationReq{} }
func (m *CreateConversationReq) String() string { return proto.CompactTextString(m) }
func (*CreateConversationReq) ProtoMessage()    {}
func (*CreateConversationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *CreateConversationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationReq.Unmarshal(m, b)
}
func (m *CreateConversationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationReq.Marshal(b, m, deterministic)
}
func (m *CreateConversationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationReq.Merge(m, src)
}
func (m *CreateConversationReq) XXX_Size() int {
	return xxx_messageInfo_CreateConversationReq.Size(m)
}
func (m *CreateConversationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationReq proto.InternalMessageInfo

func (m *CreateConversationReq) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *CreateConversationReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateConversationReq) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

type CreateConversationResp struct {
	Ok                   bool          `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Conv                 *Conversation `protobuf:"bytes,2,opt,name=conv,proto3" json:"conv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateConversationResp) Reset()         { *m = CreateConversationResp{} }
func (m *CreateConversationResp) String() string { return proto.CompactTextString(m) }
func (*CreateConversationResp) ProtoMessage()    {}
func (*CreateConversationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *CreateConversationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationResp.Unmarshal(m, b)
}
func (m *CreateConversationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationResp.Marshal(b, m, deterministic)
}
func (m *CreateConversationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationResp.Merge(m, src)
}
func (m *CreateConversationResp) XXX_Size() int {
	return xxx_messageInfo_CreateConversationResp.Size(m)
}
func (m *CreateConversationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationResp proto.InternalMessageInfo

func (m *CreateConversationResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *CreateConversationResp) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

type NotifyInvited struct {
	Conv                 *Conversation `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	InitBy               string        `protobuf:"bytes,2,opt,name=initBy,proto3" json:"initBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NotifyInvited) Reset()         { *m = NotifyInvited{} }
func (m *NotifyInvited) String() string { return proto.CompactTextString(m) }
func (*NotifyInvited) ProtoMessage()    {}
func (*NotifyInvited) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *NotifyInvited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyInvited.Unmarshal(m, b)
}
func (m *NotifyInvited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyInvited.Marshal(b, m, deterministic)
}
func (m *NotifyInvited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyInvited.Merge(m, src)
}
func (m *NotifyInvited) XXX_Size() int {
	return xxx_messageInfo_NotifyInvited.Size(m)
}
func (m *NotifyInvited) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyInvited.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyInvited proto.InternalMessageInfo

func (m *NotifyInvited) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

func (m *NotifyInvited) GetInitBy() string {
	if m != nil {
		return m.InitBy
	}
	return ""
}

// 发送消息
type Message struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SendMessageReq struct {
	Msg                  *Message `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageReq) Reset()         { *m = SendMessageReq{} }
func (m *SendMessageReq) String() string { return proto.CompactTextString(m) }
func (*SendMessageReq) ProtoMessage()    {}
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *SendMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageReq.Unmarshal(m, b)
}
func (m *SendMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageReq.Marshal(b, m, deterministic)
}
func (m *SendMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageReq.Merge(m, src)
}
func (m *SendMessageReq) XXX_Size() int {
	return xxx_messageInfo_SendMessageReq.Size(m)
}
func (m *SendMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageReq proto.InternalMessageInfo

func (m *SendMessageReq) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type SendMessageResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResp) Reset()         { *m = SendMessageResp{} }
func (m *SendMessageResp) String() string { return proto.CompactTextString(m) }
func (*SendMessageResp) ProtoMessage()    {}
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *SendMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResp.Unmarshal(m, b)
}
func (m *SendMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResp.Marshal(b, m, deterministic)
}
func (m *SendMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResp.Merge(m, src)
}
func (m *SendMessageResp) XXX_Size() int {
	return xxx_messageInfo_SendMessageResp.Size(m)
}
func (m *SendMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResp proto.InternalMessageInfo

func (m *SendMessageResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type NotifyMessage struct {
	Conv                 *Conversation `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	Msg                  *Message      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NotifyMessage) Reset()         { *m = NotifyMessage{} }
func (m *NotifyMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyMessage) ProtoMessage()    {}
func (*NotifyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *NotifyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMessage.Unmarshal(m, b)
}
func (m *NotifyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMessage.Marshal(b, m, deterministic)
}
func (m *NotifyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMessage.Merge(m, src)
}
func (m *NotifyMessage) XXX_Size() int {
	return xxx_messageInfo_NotifyMessage.Size(m)
}
func (m *NotifyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMessage proto.InternalMessageInfo

func (m *NotifyMessage) GetConv() *Conversation {
	if m != nil {
		return m.Conv
	}
	return nil
}

func (m *NotifyMessage) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*Conversation)(nil), "Conversation")
	proto.RegisterType((*CreateConversationReq)(nil), "CreateConversationReq")
	proto.RegisterType((*CreateConversationResp)(nil), "CreateConversationResp")
	proto.RegisterType((*NotifyInvited)(nil), "NotifyInvited")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*SendMessageReq)(nil), "SendMessageReq")
	proto.RegisterType((*SendMessageResp)(nil), "SendMessageResp")
	proto.RegisterType((*NotifyMessage)(nil), "NotifyMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xcd, 0x4e, 0x02, 0x31,
	0x10, 0x4e, 0x17, 0x02, 0xcb, 0xe8, 0x62, 0xd2, 0x44, 0xb2, 0x31, 0x31, 0x59, 0x7a, 0xda, 0x83,
	0xd9, 0x83, 0xbe, 0x01, 0x9c, 0xd4, 0xc8, 0xa1, 0xde, 0x4c, 0x3c, 0x2c, 0x30, 0x92, 0x06, 0xdb,
	0xc2, 0xb6, 0x6c, 0xe4, 0xed, 0x4d, 0x6b, 0x8b, 0x12, 0x31, 0xf1, 0x36, 0xd3, 0x99, 0xef, 0x67,
	0xbe, 0x42, 0x26, 0xd1, 0x98, 0x7a, 0x85, 0xd5, 0xa6, 0xd1, 0x56, 0x33, 0x06, 0xe7, 0x53, 0xad,
	0x5a, 0x6c, 0x4c, 0x6d, 0x85, 0x56, 0x94, 0x42, 0x57, 0xd5, 0x12, 0x73, 0x52, 0x90, 0x72, 0xc0,
	0x7d, 0xcd, 0x5e, 0xe1, 0x72, 0xda, 0x60, 0x6d, 0xf1, 0xe7, 0x26, 0xc7, 0x2d, 0xcd, 0xa1, 0x2f,
	0x51, 0xce, 0xb1, 0x31, 0x39, 0x29, 0x3a, 0xe5, 0x80, 0xc7, 0xf6, 0x40, 0x93, 0x7c, 0xd3, 0xd0,
	0x11, 0xf4, 0x76, 0x4a, 0x6c, 0x77, 0x98, 0x77, 0x0a, 0x52, 0xa6, 0x3c, 0x74, 0xec, 0x11, 0x46,
	0xa7, 0xe8, 0xcd, 0x86, 0x0e, 0x21, 0xd1, 0x6b, 0x6f, 0x25, 0xe5, 0x89, 0x5e, 0xd3, 0x31, 0x74,
	0x17, 0x5a, 0xb5, 0x9e, 0xf5, 0xec, 0x36, 0xab, 0x8e, 0x00, 0x7e, 0xc4, 0x1e, 0x20, 0x9b, 0x69,
	0x2b, 0xde, 0xf6, 0xf7, 0xaa, 0x15, 0x16, 0x97, 0x07, 0x0c, 0xf9, 0x13, 0xe3, 0x8c, 0x09, 0x25,
	0xec, 0x64, 0x1f, 0xec, 0x86, 0x8e, 0x5d, 0x43, 0xff, 0xe9, 0x2b, 0x2c, 0x77, 0x8f, 0xc5, 0x0f,
	0x1b, 0x63, 0x71, 0x35, 0xbb, 0x81, 0xe1, 0x33, 0xaa, 0x65, 0x58, 0x71, 0x79, 0x5c, 0x41, 0x47,
	0x9a, 0x55, 0x90, 0x4a, 0xab, 0x38, 0x71, 0x8f, 0x6c, 0x0c, 0x17, 0x47, 0xdb, 0xbf, 0xcf, 0x63,
	0xb3, 0xe8, 0x3d, 0xaa, 0xfe, 0xc3, 0x7b, 0x90, 0x4c, 0x4e, 0x48, 0x4e, 0xe0, 0x25, 0xf5, 0x9f,
	0xbc, 0xd0, 0xef, 0xf3, 0x9e, 0xaf, 0xee, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x1c, 0x1e,
	0x50, 0xff, 0x01, 0x00, 0x00,
}
